[INFO    :   django.utils.autoreload] - 2024-01-14 23:58:12,631 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :            appfirst.views] - 2024-01-14 23:58:13,873 : index @ 0013: Главная страница
[INFO    :             django.server] - 2024-01-14 23:58:13,879 : log_message @ 0212: "GET / HTTP/1.1" 200 1640
[INFO    :            appfirst.views] - 2024-01-14 23:58:16,510 : about @ 0023: Загружена страница обо мне
[INFO    :             django.server] - 2024-01-14 23:58:16,511 : log_message @ 0212: "GET /about/ HTTP/1.1" 200 115
[INFO    :            appfirst.views] - 2024-01-14 23:58:18,331 : about @ 0023: Загружена страница обо мне
[INFO    :             django.server] - 2024-01-14 23:58:18,331 : log_message @ 0212: "GET /about/ HTTP/1.1" 200 115
[INFO    :   django.utils.autoreload] - 2024-01-15 00:01:13,207 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :            appfirst.views] - 2024-01-15 00:01:23,810 : index @ 0013: Главная страница
[INFO    :             django.server] - 2024-01-15 00:01:23,815 : log_message @ 0212: "GET / HTTP/1.1" 200 1640
[INFO    :             django.server] - 2024-01-15 00:01:23,836 : log_message @ 0212: "GET /static/css/stylesheet.css HTTP/1.1" 304 0
[ERROR   : django.security.DisallowedHost] - 2024-01-15 00:01:43,600 : response_for_exception @ 0124: Invalid HTTP_HOST header: '192.168.0.113:8000'. You may need to add '192.168.0.113' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '192.168.0.113:8000'. You may need to add '192.168.0.113' to ALLOWED_HOSTS.
[WARNING :            django.request] - 2024-01-15 00:01:43,644 : log_response @ 0241: Bad Request: /
[WARNING :             django.server] - 2024-01-15 00:01:43,645 : log_message @ 0212: "GET / HTTP/1.1" 400 68790
[ERROR   : django.security.DisallowedHost] - 2024-01-15 00:01:43,862 : response_for_exception @ 0124: Invalid HTTP_HOST header: '192.168.0.113:8000'. You may need to add '192.168.0.113' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '192.168.0.113:8000'. You may need to add '192.168.0.113' to ALLOWED_HOSTS.
[WARNING :            django.request] - 2024-01-15 00:01:43,874 : log_response @ 0241: Bad Request: /favicon.ico
[WARNING :             django.server] - 2024-01-15 00:01:43,874 : log_message @ 0212: "GET /favicon.ico HTTP/1.1" 400 68761
[ERROR   : django.security.DisallowedHost] - 2024-01-15 00:02:15,983 : response_for_exception @ 0124: Invalid HTTP_HOST header: '192.168.0.113:8000'. You may need to add '192.168.0.113' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '192.168.0.113:8000'. You may need to add '192.168.0.113' to ALLOWED_HOSTS.
[WARNING :            django.request] - 2024-01-15 00:02:16,000 : log_response @ 0241: Bad Request: /
[WARNING :             django.server] - 2024-01-15 00:02:16,000 : log_message @ 0212: "GET / HTTP/1.1" 400 68927
[ERROR   : django.security.DisallowedHost] - 2024-01-15 00:02:16,242 : response_for_exception @ 0124: Invalid HTTP_HOST header: '192.168.0.113:8000'. You may need to add '192.168.0.113' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '192.168.0.113:8000'. You may need to add '192.168.0.113' to ALLOWED_HOSTS.
[WARNING :            django.request] - 2024-01-15 00:02:16,254 : log_response @ 0241: Bad Request: /favicon.ico
[WARNING :             django.server] - 2024-01-15 00:02:16,255 : log_message @ 0212: "GET /favicon.ico HTTP/1.1" 400 68761
[ERROR   : django.security.DisallowedHost] - 2024-01-15 00:02:23,301 : response_for_exception @ 0124: Invalid HTTP_HOST header: '192.168.0.113:8000'. You may need to add '192.168.0.113' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '192.168.0.113:8000'. You may need to add '192.168.0.113' to ALLOWED_HOSTS.
[WARNING :            django.request] - 2024-01-15 00:02:23,315 : log_response @ 0241: Bad Request: /about
[WARNING :             django.server] - 2024-01-15 00:02:23,315 : log_message @ 0212: "GET /about HTTP/1.1" 400 68759
[ERROR   : django.security.DisallowedHost] - 2024-01-15 00:02:23,439 : response_for_exception @ 0124: Invalid HTTP_HOST header: '192.168.0.113:8000'. You may need to add '192.168.0.113' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '192.168.0.113:8000'. You may need to add '192.168.0.113' to ALLOWED_HOSTS.
[WARNING :            django.request] - 2024-01-15 00:02:23,453 : log_response @ 0241: Bad Request: /favicon.ico
[WARNING :             django.server] - 2024-01-15 00:02:23,453 : log_message @ 0212: "GET /favicon.ico HTTP/1.1" 400 68766
[INFO    :   django.utils.autoreload] - 2024-01-15 00:03:23,358 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-15 00:03:46,962 : log_message @ 0212: "GET /about HTTP/1.1" 301 0
[INFO    :            appfirst.views] - 2024-01-15 00:03:46,972 : about @ 0023: Загружена страница обо мне
[INFO    :             django.server] - 2024-01-15 00:03:46,972 : log_message @ 0212: "GET /about/ HTTP/1.1" 200 115
[WARNING :            django.request] - 2024-01-15 00:03:47,025 : log_response @ 0241: Not Found: /favicon.ico
[WARNING :             django.server] - 2024-01-15 00:03:47,025 : log_message @ 0212: "GET /favicon.ico HTTP/1.1" 404 2612
[INFO    :            appfirst.views] - 2024-01-15 00:03:53,475 : index @ 0013: Главная страница
[INFO    :             django.server] - 2024-01-15 00:03:53,481 : log_message @ 0212: "GET / HTTP/1.1" 200 1640
[INFO    :             django.server] - 2024-01-15 00:03:53,555 : log_message @ 0212: "GET /static/css/stylesheet.css HTTP/1.1" 200 2860
[INFO    :             django.server] - 2024-01-15 00:03:53,604 : log_message @ 0212: "GET /static/image/appfirst/cat_1.jpg HTTP/1.1" 200 145712
[INFO    :             django.server] - 2024-01-15 00:03:53,618 : log_message @ 0212: "GET /static/image/appfirst/cat_2.jpg HTTP/1.1" 200 313796
[INFO    :            appfirst.views] - 2024-01-15 00:04:05,983 : about @ 0023: Загружена страница обо мне
[INFO    :             django.server] - 2024-01-15 00:04:05,984 : log_message @ 0212: "GET /about/ HTTP/1.1" 200 115
[INFO    :            appfirst.views] - 2024-01-15 00:04:07,643 : about @ 0023: Загружена страница обо мне
[INFO    :             django.server] - 2024-01-15 00:04:07,644 : log_message @ 0212: "GET /about/ HTTP/1.1" 200 115
[INFO    :             django.server] - 2024-01-15 00:04:26,271 : handle_error @ 0081: - Broken pipe from ('192.168.0.100', 43600)
[INFO    :             django.server] - 2024-01-15 00:04:26,271 : handle_error @ 0081: - Broken pipe from ('192.168.0.100', 49108)
[INFO    :             django.server] - 2024-01-15 00:04:26,271 : handle_error @ 0081: - Broken pipe from ('192.168.0.100', 49118)
[INFO    :   django.utils.autoreload] - 2024-01-15 21:05:58,666 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :            appfirst.views] - 2024-01-15 21:06:22,263 : index @ 0013: Главная страница
[INFO    :             django.server] - 2024-01-15 21:06:22,278 : log_message @ 0212: "GET / HTTP/1.1" 200 1640
[INFO    :             django.server] - 2024-01-15 21:06:22,372 : log_message @ 0212: "GET /static/image/appfirst/cat_2.jpg HTTP/1.1" 304 0
[INFO    :             django.server] - 2024-01-15 21:06:22,372 : log_message @ 0212: "GET /static/css/stylesheet.css HTTP/1.1" 304 0
[WARNING :            django.request] - 2024-01-15 21:06:22,472 : log_response @ 0241: Not Found: /favicon.ico
[WARNING :             django.server] - 2024-01-15 21:06:22,473 : log_message @ 0212: "GET /favicon.ico HTTP/1.1" 404 2608
[INFO    :            appfirst.views] - 2024-01-15 21:06:32,237 : about @ 0023: Загружена страница обо мне
[INFO    :             django.server] - 2024-01-15 21:06:32,237 : log_message @ 0212: "GET /about/ HTTP/1.1" 200 115
[INFO    :   django.utils.autoreload] - 2024-01-15 16:53:27,180 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :            appfirst.views] - 2024-01-15 16:53:29,640 : index @ 0013: Главная страница
[INFO    :             django.server] - 2024-01-15 16:53:29,657 : log_message @ 0212: "GET / HTTP/1.1" 200 1640
[INFO    :             django.server] - 2024-01-15 16:53:29,854 : log_message @ 0212: "GET /static/css/stylesheet.css HTTP/1.1" 200 2745
[INFO    :             django.server] - 2024-01-15 16:53:29,856 : log_message @ 0212: "GET /static/image/appfirst/cat_1.jpg HTTP/1.1" 200 145712
[INFO    :             django.server] - 2024-01-15 16:53:29,858 : log_message @ 0212: "GET /static/image/appfirst/cat_2.jpg HTTP/1.1" 200 313796
[WARNING :            django.request] - 2024-01-15 16:53:29,962 : log_response @ 0241: Not Found: /favicon.ico
[WARNING :             django.server] - 2024-01-15 16:53:29,963 : log_message @ 0212: "GET /favicon.ico HTTP/1.1" 404 2608
[INFO    :   django.utils.autoreload] - 2024-01-15 21:19:55,383 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-15 21:53:59,681 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-16 01:07:51,374 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :            appfirst.views] - 2024-01-16 01:07:59,434 : index @ 0013: Главная страница
[INFO    :             django.server] - 2024-01-16 01:07:59,440 : log_message @ 0212: "GET / HTTP/1.1" 200 1640
[INFO    :             django.server] - 2024-01-16 01:07:59,468 : log_message @ 0212: "GET /static/css/stylesheet.css HTTP/1.1" 304 0
[INFO    :             django.server] - 2024-01-16 01:07:59,470 : log_message @ 0212: "GET /static/image/appfirst/cat_2.jpg HTTP/1.1" 304 0
[INFO    :            appfirst.views] - 2024-01-16 01:08:01,551 : about @ 0023: Загружена страница обо мне
[INFO    :             django.server] - 2024-01-16 01:08:01,551 : log_message @ 0212: "GET /about/ HTTP/1.1" 200 132
[WARNING :            django.request] - 2024-01-16 01:08:02,677 : log_response @ 0241: Not Found: /about/{% url
[WARNING :             django.server] - 2024-01-16 01:08:02,677 : log_message @ 0212: "GET /about/%7B%%20url HTTP/1.1" 404 2617
[INFO    :   django.utils.autoreload] - 2024-01-16 01:09:58,890 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\homeworks\projecthome\appfirst\urls.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 01:09:59,227 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[WARNING :            django.request] - 2024-01-16 01:10:00,043 : log_response @ 0241: Not Found: /about/{% url
[WARNING :             django.server] - 2024-01-16 01:10:00,043 : log_message @ 0212: "GET /about/%7B%%20url HTTP/1.1" 404 2789
[INFO    :   django.utils.autoreload] - 2024-01-16 01:10:12,661 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\homeworks\projecthome\appfirst\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 01:10:12,972 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[WARNING :            django.request] - 2024-01-16 01:10:13,386 : log_response @ 0241: Not Found: /about/{% url
[WARNING :             django.server] - 2024-01-16 01:10:13,386 : log_message @ 0212: "GET /about/%7B%%20url HTTP/1.1" 404 2789
[INFO    :   django.utils.autoreload] - 2024-01-16 01:10:28,443 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\homeworks\projecthome\appfirst\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 01:10:28,751 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[WARNING :            django.request] - 2024-01-16 01:10:29,831 : log_response @ 0241: Not Found: /about/{% url
[WARNING :             django.server] - 2024-01-16 01:10:29,831 : log_message @ 0212: "GET /about/%7B%%20url HTTP/1.1" 404 2789
[WARNING :            django.request] - 2024-01-16 01:10:34,193 : log_response @ 0241: Not Found: /about/{% url
[WARNING :             django.server] - 2024-01-16 01:10:34,194 : log_message @ 0212: "GET /about/%7B%%20url HTTP/1.1" 404 2789
[WARNING :            django.request] - 2024-01-16 01:10:34,240 : log_response @ 0241: Not Found: /favicon.ico
[WARNING :             django.server] - 2024-01-16 01:10:34,240 : log_message @ 0212: "GET /favicon.ico HTTP/1.1" 404 2780
[WARNING :            django.request] - 2024-01-16 01:10:37,222 : log_response @ 0241: Not Found: /about/{% url
[WARNING :             django.server] - 2024-01-16 01:10:37,222 : log_message @ 0212: "GET /about/%7B%%20url HTTP/1.1" 404 2789
[INFO    :   django.utils.autoreload] - 2024-01-16 01:10:45,433 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[WARNING :            django.request] - 2024-01-16 01:10:47,757 : log_response @ 0241: Not Found: /about/{% url
[WARNING :             django.server] - 2024-01-16 01:10:47,758 : log_message @ 0212: "GET /about/%7B%%20url HTTP/1.1" 404 2789
[INFO    :            appfirst.views] - 2024-01-16 01:10:51,552 : about @ 0023: Загружена страница обо мне
[INFO    :             django.server] - 2024-01-16 01:10:51,553 : log_message @ 0212: "GET /about/ HTTP/1.1" 200 120
[INFO    :            appfirst.views] - 2024-01-16 01:10:53,017 : index @ 0013: Главная страница
[INFO    :             django.server] - 2024-01-16 01:10:53,022 : log_message @ 0212: "GET /about/index HTTP/1.1" 200 1651
[INFO    :            appfirst.views] - 2024-01-16 01:11:00,699 : about @ 0023: Загружена страница обо мне
[INFO    :             django.server] - 2024-01-16 01:11:00,699 : log_message @ 0212: "GET /about/ HTTP/1.1" 200 120
[INFO    :            appfirst.views] - 2024-01-16 01:11:04,124 : index @ 0013: Главная страница
[INFO    :             django.server] - 2024-01-16 01:11:04,125 : log_message @ 0212: "GET /about/index HTTP/1.1" 200 1651
[INFO    :   django.utils.autoreload] - 2024-01-16 01:12:02,150 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\homeworks\projecthome\appfirst\urls.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 01:12:02,472 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-16 01:12:10,531 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-16 09:06:52,453 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-16 09:06:59,959 : log_message @ 0212: "GET /static/css/stylesheet.css HTTP/1.1" 304 0
[INFO    :             django.server] - 2024-01-16 09:06:59,960 : log_message @ 0212: "GET /static/image/appfirst/cat_2.jpg HTTP/1.1" 304 0
[WARNING :            django.request] - 2024-01-16 09:07:00,050 : log_response @ 0241: Not Found: /favicon.ico
[WARNING :             django.server] - 2024-01-16 09:07:00,050 : log_message @ 0212: "GET /favicon.ico HTTP/1.1" 404 2608
[INFO    :   django.utils.autoreload] - 2024-01-16 14:53:39,346 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-16 14:54:37,518 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\homeworks\projecthome\appfirst\models.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 14:54:48,385 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :            appfirst.views] - 2024-01-16 14:54:50,745 : index @ 0013: Главная страница
[INFO    :             django.server] - 2024-01-16 14:54:50,760 : log_message @ 0212: "GET / HTTP/1.1" 200 1640
[INFO    :             django.server] - 2024-01-16 14:54:50,797 : log_message @ 0212: "GET /static/css/stylesheet.css HTTP/1.1" 304 0
[INFO    :             django.server] - 2024-01-16 14:54:50,801 : log_message @ 0212: "GET /static/image/appfirst/cat_2.jpg HTTP/1.1" 304 0
[INFO    :   django.utils.autoreload] - 2024-01-16 15:14:46,160 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :            appfirst.views] - 2024-01-16 15:14:50,088 : index @ 0013: Главная страница
[INFO    :             django.server] - 2024-01-16 15:14:50,093 : log_message @ 0212: "GET / HTTP/1.1" 200 1660
[INFO    :            appfirst.views] - 2024-01-16 15:14:52,268 : index @ 0013: Главная страница
[INFO    :             django.server] - 2024-01-16 15:14:52,269 : log_message @ 0212: "GET / HTTP/1.1" 200 1660
[INFO    :             django.server] - 2024-01-16 15:14:52,346 : log_message @ 0212: "GET /static/css/stylesheet.css HTTP/1.1" 200 2860
[INFO    :             django.server] - 2024-01-16 15:14:52,348 : log_message @ 0212: "GET /static/image/appfirst/cat_2.jpg HTTP/1.1" 200 313796
[INFO    :             django.server] - 2024-01-16 15:14:52,349 : log_message @ 0212: "GET /static/image/appfirst/cat_1.jpg HTTP/1.1" 200 145712
[WARNING :            django.request] - 2024-01-16 15:14:52,371 : log_response @ 0241: Not Found: /favicon.ico
[WARNING :             django.server] - 2024-01-16 15:14:52,371 : log_message @ 0212: "GET /favicon.ico HTTP/1.1" 404 2608
[INFO    :            appfirst.views] - 2024-01-16 15:15:05,472 : index @ 0013: Главная страница
[INFO    :             django.server] - 2024-01-16 15:15:05,473 : log_message @ 0212: "GET / HTTP/1.1" 200 1660
[INFO    :            appfirst.views] - 2024-01-16 15:18:07,614 : index @ 0013: Главная страница
[INFO    :             django.server] - 2024-01-16 15:18:07,618 : log_message @ 0212: "GET / HTTP/1.1" 200 1694
[INFO    :            appfirst.views] - 2024-01-16 15:18:55,061 : index @ 0013: Главная страница
[INFO    :             django.server] - 2024-01-16 15:18:55,066 : log_message @ 0212: "GET / HTTP/1.1" 200 1704
[INFO    :            appfirst.views] - 2024-01-16 15:25:22,936 : index @ 0013: Главная страница
[INFO    :             django.server] - 2024-01-16 15:25:22,937 : log_message @ 0212: "GET / HTTP/1.1" 200 1704
[INFO    :   django.utils.autoreload] - 2024-01-16 15:26:27,802 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\homeworks\projecthome\appfirst\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 15:26:28,138 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-16 15:41:17,227 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\homeworks\projecthome\appfirst\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 15:41:17,570 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :            appfirst.views] - 2024-01-16 15:41:53,620 : index @ 0014: Главная страница
[INFO    :             django.server] - 2024-01-16 15:41:53,630 : log_message @ 0212: "GET / HTTP/1.1" 200 1704
[INFO    :   django.utils.autoreload] - 2024-01-16 15:42:39,288 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\homeworks\projecthome\appfirst\urls.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 15:42:39,728 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :            appfirst.views] - 2024-01-16 15:42:42,820 : index @ 0014: Главная страница
[INFO    :             django.server] - 2024-01-16 15:42:42,825 : log_message @ 0212: "GET / HTTP/1.1" 200 1704
[INFO    :             django.server] - 2024-01-16 15:42:42,901 : log_message @ 0212: "GET /static/css/stylesheet.css HTTP/1.1" 200 2860
[INFO    :             django.server] - 2024-01-16 15:42:42,901 : log_message @ 0212: "GET /static/image/appfirst/cat_1.jpg HTTP/1.1" 200 145712
[INFO    :             django.server] - 2024-01-16 15:42:42,902 : log_message @ 0212: "GET /static/image/appfirst/cat_2.jpg HTTP/1.1" 200 313796
[WARNING :            django.request] - 2024-01-16 15:42:42,925 : log_response @ 0241: Not Found: /favicon.ico
[WARNING :             django.server] - 2024-01-16 15:42:42,925 : log_message @ 0212: "GET /favicon.ico HTTP/1.1" 404 2786
[INFO    :            appfirst.views] - 2024-01-16 15:43:20,198 : index @ 0014: Главная страница
[ERROR   :            django.request] - 2024-01-16 15:43:20,241 : log_response @ 0241: Internal Server Error: /
Traceback (most recent call last):
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\homeworks\projecthome\appfirst\views.py", line 15, in index
    return render(request, 'appfirst/index.html', context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\defaulttags.py", line 478, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\urls\resolvers.py", line 848, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'edit_judge' not found. 'edit_judge' is not a valid view function or pattern name.
[ERROR   :             django.server] - 2024-01-16 15:43:20,245 : log_message @ 0212: "GET / HTTP/1.1" 500 144382
[INFO    :            appfirst.views] - 2024-01-16 15:43:35,962 : index @ 0014: Главная страница
[INFO    :             django.server] - 2024-01-16 15:43:35,967 : log_message @ 0212: "GET / HTTP/1.1" 200 1715
[ERROR   :            django.request] - 2024-01-16 15:43:37,708 : log_response @ 0241: Internal Server Error: /edit_judge/
Traceback (most recent call last):
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\homeworks\projecthome\appfirst\views.py", line 20, in edit_judges
    return render(request, 'appfirst/edit_judges.html', context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: appfirst/edit_judges.html
[ERROR   :             django.server] - 2024-01-16 15:43:37,709 : log_message @ 0212: "GET /edit_judge/ HTTP/1.1" 500 80794
[ERROR   :            django.request] - 2024-01-16 15:44:03,256 : log_response @ 0241: Internal Server Error: /edit_judge/
Traceback (most recent call last):
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\homeworks\projecthome\appfirst\views.py", line 20, in edit_judges
    return render(request, 'appfirst/edit_judges.html', context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\backends\django.py", line 57, in render
    context = make_context(
              ^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\context.py", line 286, in make_context
    raise TypeError(
TypeError: context must be a dict rather than QuerySet.
[ERROR   :             django.server] - 2024-01-16 15:44:03,257 : log_message @ 0212: "GET /edit_judge/ HTTP/1.1" 500 82633
[INFO    :   django.utils.autoreload] - 2024-01-16 15:44:32,057 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\homeworks\projecthome\appfirst\urls.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 15:44:32,395 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[WARNING :            django.request] - 2024-01-16 15:44:32,997 : log_response @ 0241: Not Found: /edit_judge/
[WARNING :             django.server] - 2024-01-16 15:44:32,997 : log_message @ 0212: "GET /edit_judge/ HTTP/1.1" 404 2787
[INFO    :            appfirst.views] - 2024-01-16 15:44:40,348 : index @ 0014: Главная страница
[INFO    :             django.server] - 2024-01-16 15:44:40,352 : log_message @ 0212: "GET / HTTP/1.1" 200 1716
[ERROR   :            django.request] - 2024-01-16 15:44:41,891 : log_response @ 0241: Internal Server Error: /edit_judges/
Traceback (most recent call last):
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\homeworks\projecthome\appfirst\views.py", line 20, in edit_judges
    return render(request, 'appfirst/edit_judges.html', context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\backends\django.py", line 57, in render
    context = make_context(
              ^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\context.py", line 286, in make_context
    raise TypeError(
TypeError: context must be a dict rather than QuerySet.
[ERROR   :             django.server] - 2024-01-16 15:44:41,892 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 500 82510
[INFO    :   django.utils.autoreload] - 2024-01-16 15:44:54,127 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\homeworks\projecthome\appfirst\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 15:44:54,483 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-16 15:44:54,800 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 1187
[INFO    :             django.server] - 2024-01-16 15:48:50,901 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 1187
[INFO    :   django.utils.autoreload] - 2024-01-16 15:57:39,212 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\homeworks\projecthome\appfirst\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 15:57:39,561 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-16 15:57:42,049 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 1187
[INFO    :   django.utils.autoreload] - 2024-01-16 15:57:52,047 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\homeworks\projecthome\appfirst\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 15:57:52,380 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-16 15:57:52,548 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 1187
[INFO    :   django.utils.autoreload] - 2024-01-16 15:58:24,139 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\homeworks\projecthome\appfirst\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 15:58:24,458 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :            appfirst.views] - 2024-01-16 15:58:25,231 : index @ 0014: Главная страница
[INFO    :             django.server] - 2024-01-16 15:58:25,236 : log_message @ 0212: "GET / HTTP/1.1" 200 1716
[INFO    :             django.server] - 2024-01-16 15:58:26,884 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 1187
[INFO    :   django.utils.autoreload] - 2024-01-16 15:58:58,266 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\homeworks\projecthome\appfirst\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 15:58:58,592 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-16 15:58:58,880 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 1187
[INFO    :   django.utils.autoreload] - 2024-01-16 15:59:19,156 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\homeworks\projecthome\appfirst\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 15:59:19,476 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-16 15:59:19,705 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 1187
[INFO    :   django.utils.autoreload] - 2024-01-16 16:00:20,777 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\homeworks\projecthome\appfirst\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 16:00:21,134 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-16 16:00:22,607 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 1187
[INFO    :   django.utils.autoreload] - 2024-01-16 16:02:23,587 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\homeworks\projecthome\appfirst\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 16:02:23,917 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-16 16:02:25,231 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 1187
[INFO    :   django.utils.autoreload] - 2024-01-16 16:08:42,076 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\homeworks\projecthome\appfirst\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 16:08:42,424 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-16 16:08:44,510 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 1187
[INFO    :             django.server] - 2024-01-16 16:16:04,150 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 1187
[INFO    :   django.utils.autoreload] - 2024-01-16 16:17:05,670 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\homeworks\projecthome\appfirst\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 16:17:06,021 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[ERROR   :            django.request] - 2024-01-16 16:17:08,618 : log_response @ 0241: Internal Server Error: /edit_judges/
Traceback (most recent call last):
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\homeworks\projecthome\appfirst\views.py", line 21, in edit_judges
    list_result = {judge for judge in context}
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\homeworks\projecthome\appfirst\views.py", line 21, in <setcomp>
    list_result = {judge for judge in context}
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unhashable type: 'dict'
[ERROR   :             django.server] - 2024-01-16 16:17:08,619 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 500 70841
[INFO    :   django.utils.autoreload] - 2024-01-16 16:28:16,518 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\homeworks\projecthome\appfirst\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 16:28:16,848 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-16 16:29:01,145 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 1246
[ERROR   :            django.request] - 2024-01-16 16:29:39,803 : log_response @ 0241: Internal Server Error: /edit_judges/
Traceback (most recent call last):
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\homeworks\projecthome\appfirst\views.py", line 23, in edit_judges
    return render(request, 'appfirst/edit_judges.html', context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\defaulttags.py", line 859, in do_for
    sequence = parser.compile_filter(bits[in_index + 1])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 597, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 698, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '['judges']' from 'context['judges']'
[ERROR   :             django.server] - 2024-01-16 16:29:39,807 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 500 182524
[INFO    :             django.server] - 2024-01-16 16:33:00,841 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 1246
[ERROR   :            django.request] - 2024-01-16 16:33:44,109 : log_response @ 0241: Internal Server Error: /edit_judges/
Traceback (most recent call last):
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\homeworks\projecthome\appfirst\views.py", line 23, in edit_judges
    return render(request, 'appfirst/edit_judges.html', context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\defaulttags.py", line 860, in do_for
    nodelist_loop = parser.parse(
                    ^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 481, in parse
    raise self.error(token, e)
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 479, in parse
    filter_expression = self.compile_filter(token.contents)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 597, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 698, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '[name]' from 'judje[name]'
[ERROR   :             django.server] - 2024-01-16 16:33:44,113 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 500 190733
[ERROR   :            django.request] - 2024-01-16 16:34:03,551 : log_response @ 0241: Internal Server Error: /edit_judges/
Traceback (most recent call last):
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\homeworks\projecthome\appfirst\views.py", line 23, in edit_judges
    return render(request, 'appfirst/edit_judges.html', context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\defaulttags.py", line 860, in do_for
    nodelist_loop = parser.parse(
                    ^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 481, in parse
    raise self.error(token, e)
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 479, in parse
    filter_expression = self.compile_filter(token.contents)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 597, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 698, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '['name']' from 'judje['name']'
[ERROR   :             django.server] - 2024-01-16 16:34:03,553 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 500 190997
[ERROR   :            django.request] - 2024-01-16 16:36:32,759 : log_response @ 0241: Internal Server Error: /edit_judges/
Traceback (most recent call last):
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\homeworks\projecthome\appfirst\views.py", line 23, in edit_judges
    return render(request, 'appfirst/edit_judges.html', context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\defaulttags.py", line 241, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\defaulttags.py", line 229, in render
    raise ValueError(
ValueError: Need 2 values to unpack in for loop; got 4. 
[ERROR   :             django.server] - 2024-01-16 16:36:32,766 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 500 183757
[INFO    :             django.server] - 2024-01-16 16:36:42,459 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 2337
[INFO    :             django.server] - 2024-01-16 16:37:18,913 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 2337
[INFO    :   django.utils.autoreload] - 2024-01-16 16:38:14,887 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :            appfirst.views] - 2024-01-16 16:38:21,781 : index @ 0014: Главная страница
[INFO    :             django.server] - 2024-01-16 16:38:21,786 : log_message @ 0212: "GET / HTTP/1.1" 200 1716
[INFO    :             django.server] - 2024-01-16 16:38:28,323 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 2337
[INFO    :             django.server] - 2024-01-16 16:41:40,363 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 2355
[INFO    :   django.utils.autoreload] - 2024-01-16 16:47:16,027 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\homeworks\projecthome\appfirst\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 16:47:16,353 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-16 16:47:42,892 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\homeworks\projecthome\appfirst\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 16:47:43,206 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-16 16:47:51,413 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\homeworks\projecthome\appfirst\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 16:47:51,724 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-16 16:48:00,959 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\homeworks\projecthome\appfirst\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 16:48:01,279 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-16 16:48:12,529 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\homeworks\projecthome\appfirst\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 16:48:12,838 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-16 16:49:32,209 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\homeworks\projecthome\appfirst\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 16:49:32,541 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-16 16:53:47,146 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 2679
[INFO    :   django.utils.autoreload] - 2024-01-16 16:56:01,751 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\homeworks\projecthome\appfirst\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 16:56:02,077 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-16 16:56:02,446 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 2680
[INFO    :            appfirst.views] - 2024-01-16 16:56:51,630 : index @ 0014: Главная страница
[INFO    :             django.server] - 2024-01-16 16:56:51,631 : log_message @ 0212: "GET / HTTP/1.1" 200 1716
[INFO    :             django.server] - 2024-01-16 16:56:53,094 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 2680
[INFO    :            appfirst.views] - 2024-01-16 16:56:54,503 : about @ 0036: Загружена страница обо мне
[INFO    :             django.server] - 2024-01-16 16:56:54,504 : log_message @ 0212: "GET /about/ HTTP/1.1" 200 120
[INFO    :             django.server] - 2024-01-16 16:56:57,429 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 2680
[INFO    :   django.utils.autoreload] - 2024-01-16 16:59:15,686 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\homeworks\projecthome\appfirst\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 16:59:16,024 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-16 16:59:20,644 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 2739
[INFO    :             django.server] - 2024-01-16 17:10:01,579 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 2739
[INFO    :            appfirst.views] - 2024-01-16 17:10:02,830 : index @ 0014: Главная страница
[INFO    :             django.server] - 2024-01-16 17:10:02,832 : log_message @ 0212: "GET / HTTP/1.1" 200 1716
[INFO    :            appfirst.views] - 2024-01-16 17:10:03,929 : index @ 0014: Главная страница
[INFO    :             django.server] - 2024-01-16 17:10:03,930 : log_message @ 0212: "GET / HTTP/1.1" 200 1716
[INFO    :            appfirst.views] - 2024-01-16 17:17:17,409 : index @ 0014: Главная страница
[INFO    :             django.server] - 2024-01-16 17:17:17,411 : log_message @ 0212: "GET / HTTP/1.1" 200 1716
[INFO    :             django.server] - 2024-01-16 17:17:18,984 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 7092
[INFO    :             django.server] - 2024-01-16 17:19:47,215 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 7367
[WARNING :            django.request] - 2024-01-16 17:48:47,977 : log_response @ 0241: Not Found: /about/index
[WARNING :             django.server] - 2024-01-16 17:48:47,977 : log_message @ 0212: "GET /about/index HTTP/1.1" 404 2787
[INFO    :   django.utils.autoreload] - 2024-01-16 17:48:56,860 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :            appfirst.views] - 2024-01-16 17:49:03,674 : index @ 0014: Главная страница
[INFO    :             django.server] - 2024-01-16 17:49:03,679 : log_message @ 0212: "GET / HTTP/1.1" 200 1716
[INFO    :            appfirst.views] - 2024-01-16 17:49:10,005 : index @ 0014: Главная страница
[INFO    :             django.server] - 2024-01-16 17:49:10,006 : log_message @ 0212: "GET / HTTP/1.1" 200 1716
[INFO    :             django.server] - 2024-01-16 17:49:12,529 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 9118
[INFO    :             django.server] - 2024-01-16 17:51:35,950 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 2750
[INFO    :             django.server] - 2024-01-16 17:53:03,662 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 18097
[INFO    :             django.server] - 2024-01-16 18:05:42,180 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 5756
[INFO    :             django.server] - 2024-01-16 18:09:55,820 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 5144
[INFO    :             django.server] - 2024-01-16 18:20:43,484 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 5144
[INFO    :             django.server] - 2024-01-16 18:20:46,069 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 5144
[INFO    :             django.server] - 2024-01-16 18:20:48,862 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 5144
[INFO    :             django.server] - 2024-01-16 18:20:48,914 : log_message @ 0212: "GET /static/css/stylesheet.css HTTP/1.1" 200 6444
[WARNING :            django.request] - 2024-01-16 18:20:48,948 : log_response @ 0241: Not Found: /favicon.ico
[WARNING :             django.server] - 2024-01-16 18:20:48,948 : log_message @ 0212: "GET /favicon.ico HTTP/1.1" 404 2787
[INFO    :             django.server] - 2024-01-16 18:23:27,496 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 5144
[INFO    :             django.server] - 2024-01-16 18:23:27,519 : log_message @ 0212: "GET /static/css/stylesheet.css HTTP/1.1" 200 6490
[INFO    :             django.server] - 2024-01-16 18:38:06,953 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 5144
[INFO    :             django.server] - 2024-01-16 18:38:06,972 : log_message @ 0212: "GET /static/css/stylesheet.css HTTP/1.1" 200 6572
[INFO    :            appfirst.views] - 2024-01-16 18:38:12,011 : index @ 0014: Главная страница
[INFO    :             django.server] - 2024-01-16 18:38:12,012 : log_message @ 0212: "GET / HTTP/1.1" 200 1716
[INFO    :             django.server] - 2024-01-16 18:38:12,040 : log_message @ 0212: "GET /static/css/stylesheet.css HTTP/1.1" 304 0
[INFO    :            appfirst.views] - 2024-01-16 18:38:27,901 : index @ 0014: Главная страница
[INFO    :             django.server] - 2024-01-16 18:38:27,902 : log_message @ 0212: "GET / HTTP/1.1" 200 1716
[INFO    :             django.server] - 2024-01-16 18:38:27,924 : log_message @ 0212: "GET /static/css/stylesheet.css HTTP/1.1" 200 6595
[INFO    :            appfirst.views] - 2024-01-16 18:39:42,659 : index @ 0014: Главная страница
[INFO    :             django.server] - 2024-01-16 18:39:42,660 : log_message @ 0212: "GET / HTTP/1.1" 200 1716
[INFO    :             django.server] - 2024-01-16 18:39:42,684 : log_message @ 0212: "GET /static/css/stylesheet.css HTTP/1.1" 200 6519
[INFO    :             django.server] - 2024-01-16 18:39:45,126 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 5144
[INFO    :             django.server] - 2024-01-16 18:39:45,150 : log_message @ 0212: "GET /static/css/stylesheet.css HTTP/1.1" 304 0
[INFO    :             django.server] - 2024-01-16 18:42:15,081 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 3597
[INFO    :             django.server] - 2024-01-16 18:42:15,105 : log_message @ 0212: "GET /static/css/stylesheet.css HTTP/1.1" 304 0
[INFO    :             django.server] - 2024-01-16 18:46:11,910 : log_message @ 0212: "GET /static/css/stylesheet.css HTTP/1.1" 200 6559
[INFO    :             django.server] - 2024-01-16 18:48:42,013 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 3610
[INFO    :             django.server] - 2024-01-16 18:48:42,040 : log_message @ 0212: "GET /static/css/stylesheet.css HTTP/1.1" 304 0
[INFO    :             django.server] - 2024-01-16 18:49:17,319 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 3596
[INFO    :             django.server] - 2024-01-16 18:49:17,349 : log_message @ 0212: "GET /static/css/stylesheet.css HTTP/1.1" 304 0
[INFO    :             django.server] - 2024-01-16 18:49:23,209 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 3596
[INFO    :             django.server] - 2024-01-16 18:49:29,240 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 3596
[INFO    :             django.server] - 2024-01-16 18:51:36,945 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 3596
[INFO    :             django.server] - 2024-01-16 18:51:36,974 : log_message @ 0212: "GET /static/css/stylesheet.css HTTP/1.1" 200 6564
[INFO    :             django.server] - 2024-01-16 18:51:48,703 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 3596
[INFO    :             django.server] - 2024-01-16 18:51:48,726 : log_message @ 0212: "GET /static/css/stylesheet.css HTTP/1.1" 200 6560
[INFO    :             django.server] - 2024-01-16 18:53:56,516 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 3596
[INFO    :             django.server] - 2024-01-16 18:53:56,541 : log_message @ 0212: "GET /static/css/stylesheet.css HTTP/1.1" 200 6539
[INFO    :             django.server] - 2024-01-16 18:54:30,316 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 3596
[INFO    :             django.server] - 2024-01-16 18:54:30,342 : log_message @ 0212: "GET /static/css/stylesheet.css HTTP/1.1" 200 6546
[INFO    :             django.server] - 2024-01-16 18:54:42,588 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 3596
[INFO    :             django.server] - 2024-01-16 18:54:42,607 : log_message @ 0212: "GET /static/css/stylesheet.css HTTP/1.1" 200 6560
[INFO    :             django.server] - 2024-01-16 18:54:56,318 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 3596
[INFO    :             django.server] - 2024-01-16 18:54:56,338 : log_message @ 0212: "GET /static/css/stylesheet.css HTTP/1.1" 200 6531
[INFO    :            appfirst.views] - 2024-01-16 18:55:02,061 : index @ 0014: Главная страница
[INFO    :             django.server] - 2024-01-16 18:55:02,062 : log_message @ 0212: "GET / HTTP/1.1" 200 1716
[INFO    :             django.server] - 2024-01-16 18:55:02,084 : log_message @ 0212: "GET /static/css/stylesheet.css HTTP/1.1" 304 0
[INFO    :            appfirst.views] - 2024-01-16 18:55:07,116 : index @ 0014: Главная страница
[INFO    :             django.server] - 2024-01-16 18:55:07,116 : log_message @ 0212: "GET / HTTP/1.1" 200 1716
[INFO    :             django.server] - 2024-01-16 18:55:07,138 : log_message @ 0212: "GET /static/css/stylesheet.css HTTP/1.1" 200 6560
[INFO    :             django.server] - 2024-01-16 18:55:09,491 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 3596
[INFO    :             django.server] - 2024-01-16 18:55:09,511 : log_message @ 0212: "GET /static/css/stylesheet.css HTTP/1.1" 304 0
[INFO    :             django.server] - 2024-01-16 18:55:37,413 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 3596
[INFO    :             django.server] - 2024-01-16 18:55:37,436 : log_message @ 0212: "GET /static/css/stylesheet.css HTTP/1.1" 200 6452
[INFO    :             django.server] - 2024-01-16 18:55:57,575 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 3596
[INFO    :             django.server] - 2024-01-16 18:55:57,597 : log_message @ 0212: "GET /static/css/stylesheet.css HTTP/1.1" 200 6560
[INFO    :             django.server] - 2024-01-16 18:56:14,908 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 3596
[INFO    :             django.server] - 2024-01-16 18:56:14,928 : log_message @ 0212: "GET /static/css/stylesheet.css HTTP/1.1" 304 0
[INFO    :             django.server] - 2024-01-16 18:56:22,338 : log_message @ 0212: "GET /static/css/stylesheet.css HTTP/1.1" 304 0
[INFO    :             django.server] - 2024-01-16 18:58:02,444 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 3626
[INFO    :             django.server] - 2024-01-16 18:58:02,478 : log_message @ 0212: "GET /static/css/stylesheet.css HTTP/1.1" 200 6565
[INFO    :             django.server] - 2024-01-16 18:58:20,716 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 3626
[INFO    :             django.server] - 2024-01-16 18:58:20,739 : log_message @ 0212: "GET /static/css/stylesheet.css HTTP/1.1" 200 6566
[INFO    :             django.server] - 2024-01-16 18:58:45,147 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 3716
[INFO    :             django.server] - 2024-01-16 18:58:45,181 : log_message @ 0212: "GET /static/css/stylesheet.css HTTP/1.1" 304 0
[INFO    :             django.server] - 2024-01-16 19:00:07,428 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 3596
[INFO    :             django.server] - 2024-01-16 19:00:07,452 : log_message @ 0212: "GET /static/css/stylesheet.css HTTP/1.1" 200 6560
[INFO    :             django.server] - 2024-01-16 19:01:31,322 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 3683
[INFO    :             django.server] - 2024-01-16 19:01:31,348 : log_message @ 0212: "GET /static/css/stylesheet.css HTTP/1.1" 200 6566
[INFO    :            appfirst.views] - 2024-01-16 19:02:14,579 : about @ 0036: Загружена страница обо мне
[INFO    :             django.server] - 2024-01-16 19:02:14,579 : log_message @ 0212: "GET /about/ HTTP/1.1" 200 120
[INFO    :            appfirst.views] - 2024-01-16 19:02:15,892 : about @ 0036: Загружена страница обо мне
[INFO    :             django.server] - 2024-01-16 19:02:15,892 : log_message @ 0212: "GET /about/ HTTP/1.1" 200 120
[WARNING :            django.request] - 2024-01-16 19:02:15,928 : log_response @ 0241: Not Found: /favicon.ico
[WARNING :             django.server] - 2024-01-16 19:02:15,928 : log_message @ 0212: "GET /favicon.ico HTTP/1.1" 404 2787
[WARNING :            django.request] - 2024-01-16 19:02:17,497 : log_response @ 0241: Not Found: /about/index
[WARNING :             django.server] - 2024-01-16 19:02:17,497 : log_message @ 0212: "GET /about/index HTTP/1.1" 404 2787
[INFO    :            appfirst.views] - 2024-01-16 19:02:22,752 : index @ 0014: Главная страница
[INFO    :             django.server] - 2024-01-16 19:02:22,754 : log_message @ 0212: "GET / HTTP/1.1" 200 1831
[INFO    :             django.server] - 2024-01-16 19:02:22,781 : log_message @ 0212: "GET /static/css/stylesheet.css HTTP/1.1" 304 0
[INFO    :             django.server] - 2024-01-16 19:02:34,182 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 3711
[INFO    :             django.server] - 2024-01-16 19:02:34,208 : log_message @ 0212: "GET /static/css/stylesheet.css HTTP/1.1" 304 0
[INFO    :            appfirst.views] - 2024-01-16 19:04:32,067 : about @ 0036: Загружена страница обо мне
[INFO    :             django.server] - 2024-01-16 19:04:32,067 : log_message @ 0212: "GET /about/ HTTP/1.1" 200 120
[INFO    :            appfirst.views] - 2024-01-16 19:04:32,902 : about @ 0036: Загружена страница обо мне
[INFO    :             django.server] - 2024-01-16 19:04:32,902 : log_message @ 0212: "GET /about/ HTTP/1.1" 200 120
[WARNING :            django.request] - 2024-01-16 19:04:32,934 : log_response @ 0241: Not Found: /favicon.ico
[WARNING :             django.server] - 2024-01-16 19:04:32,934 : log_message @ 0212: "GET /favicon.ico HTTP/1.1" 404 2787
[INFO    :            appfirst.views] - 2024-01-16 19:04:36,774 : index @ 0014: Главная страница
[INFO    :             django.server] - 2024-01-16 19:04:36,775 : log_message @ 0212: "GET / HTTP/1.1" 200 1836
[INFO    :             django.server] - 2024-01-16 19:04:36,801 : log_message @ 0212: "GET /static/css/stylesheet.css HTTP/1.1" 304 0
[INFO    :             django.server] - 2024-01-16 19:04:43,900 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 3716
[INFO    :             django.server] - 2024-01-16 19:06:38,032 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 3661
[INFO    :             django.server] - 2024-01-16 19:06:38,058 : log_message @ 0212: "GET /static/css/stylesheet.css HTTP/1.1" 304 0
[INFO    :             django.server] - 2024-01-16 19:10:48,207 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 4523
[INFO    :             django.server] - 2024-01-16 19:10:48,242 : log_message @ 0212: "GET /static/css/stylesheet.css HTTP/1.1" 304 0
[INFO    :   django.utils.autoreload] - 2024-01-16 21:36:39,969 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :            appfirst.views] - 2024-01-16 21:36:51,254 : index @ 0014: Главная страница
[INFO    :             django.server] - 2024-01-16 21:36:51,274 : log_message @ 0212: "GET / HTTP/1.1" 200 1781
[INFO    :             django.server] - 2024-01-16 21:36:51,436 : log_message @ 0212: "GET /static/image/appfirst/cat_2.jpg HTTP/1.1" 200 313796
[INFO    :             django.server] - 2024-01-16 21:36:51,442 : log_message @ 0212: "GET /static/image/appfirst/cat_1.jpg HTTP/1.1" 200 145712
[INFO    :             django.server] - 2024-01-16 21:36:51,452 : log_message @ 0212: "GET /static/css/stylesheet.css HTTP/1.1" 200 6569
[WARNING :            django.request] - 2024-01-16 21:36:51,637 : log_response @ 0241: Not Found: /favicon.ico
[WARNING :             django.server] - 2024-01-16 21:36:51,638 : log_message @ 0212: "GET /favicon.ico HTTP/1.1" 404 2787
[INFO    :             django.server] - 2024-01-16 21:36:54,806 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 4523
[WARNING :            django.request] - 2024-01-16 21:37:26,802 : log_response @ 0241: Not Found: /favicon.ico
[WARNING :             django.server] - 2024-01-16 21:37:26,803 : log_message @ 0212: "GET /favicon.ico HTTP/1.1" 404 2787
[INFO    :   django.utils.autoreload] - 2024-01-16 21:39:23,797 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-16 21:39:24,972 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 1928
[INFO    :             django.server] - 2024-01-16 21:39:25,061 : log_message @ 0212: "GET /static/css/stylesheet.css HTTP/1.1" 200 6569
[WARNING :            django.request] - 2024-01-16 21:39:25,118 : log_response @ 0241: Not Found: /favicon.ico
[WARNING :             django.server] - 2024-01-16 21:39:25,119 : log_message @ 0212: "GET /favicon.ico HTTP/1.1" 404 2787
[INFO    :             django.server] - 2024-01-16 21:39:33,993 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 1928
[INFO    :             django.server] - 2024-01-16 21:39:34,021 : log_message @ 0212: "GET /static/css/stylesheet.css HTTP/1.1" 200 6569
[INFO    :   django.utils.autoreload] - 2024-01-16 21:39:34,058 : trigger_reload @ 0266: C:\Users\Администратор\PycharmProjects\24.01_Django\homeworks\projecthome\appfirst\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 21:39:34,834 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[WARNING :            django.request] - 2024-01-16 21:39:34,974 : log_response @ 0241: Not Found: /favicon.ico
[WARNING :             django.server] - 2024-01-16 21:39:34,974 : log_message @ 0212: "GET /favicon.ico HTTP/1.1" 404 2787
[INFO    :             django.server] - 2024-01-16 21:39:36,927 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 2322
[INFO    :            appfirst.views] - 2024-01-16 21:45:22,074 : index @ 0014: Главная страница
[INFO    :             django.server] - 2024-01-16 21:45:22,078 : log_message @ 0212: "GET / HTTP/1.1" 200 1781
[INFO    :             django.server] - 2024-01-16 21:45:25,420 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 2322
[INFO    :   django.utils.autoreload] - 2024-01-16 21:46:09,522 : trigger_reload @ 0266: C:\Users\Администратор\PycharmProjects\24.01_Django\homeworks\projecthome\appfirst\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 21:46:10,760 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-16 21:46:11,112 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 3661
[INFO    :             django.server] - 2024-01-16 21:46:11,366 : log_message @ 0212: "GET /static/css/stylesheet.css HTTP/1.1" 200 6569
[WARNING :            django.request] - 2024-01-16 21:46:11,482 : log_response @ 0241: Not Found: /favicon.ico
[WARNING :             django.server] - 2024-01-16 21:46:11,482 : log_message @ 0212: "GET /favicon.ico HTTP/1.1" 404 2787
[INFO    :             django.server] - 2024-01-16 21:46:12,852 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 3661
[INFO    :   django.utils.autoreload] - 2024-01-16 21:49:45,844 : trigger_reload @ 0266: C:\Users\Администратор\PycharmProjects\24.01_Django\homeworks\projecthome\appfirst\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 21:49:47,106 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-16 21:54:07,778 : trigger_reload @ 0266: C:\Users\Администратор\PycharmProjects\24.01_Django\homeworks\projecthome\appfirst\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 21:54:08,876 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-16 21:58:14,091 : trigger_reload @ 0266: C:\Users\Администратор\PycharmProjects\24.01_Django\homeworks\projecthome\appfirst\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 21:58:15,277 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-16 22:00:16,184 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-16 22:02:30,094 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[ERROR   :            django.request] - 2024-01-16 22:02:39,993 : log_response @ 0241: Internal Server Error: /edit_judges/
Traceback (most recent call last):
  File "C:\Users\Администратор\PycharmProjects\24.01_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Администратор\PycharmProjects\24.01_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Администратор\PycharmProjects\24.01_Django\homeworks\projecthome\appfirst\views.py", line 23, in edit_judges
    print(judge.name)
          ^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'name'
[ERROR   :             django.server] - 2024-01-16 22:02:39,996 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 500 73544
[INFO    :   django.utils.autoreload] - 2024-01-16 22:03:24,633 : trigger_reload @ 0266: C:\Users\Администратор\PycharmProjects\24.01_Django\homeworks\projecthome\appfirst\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 22:03:25,826 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-16 22:03:26,221 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 3687
[INFO    :             django.server] - 2024-01-16 22:03:26,302 : log_message @ 0212: "GET /static/css/stylesheet.css HTTP/1.1" 304 0
[INFO    :   django.utils.autoreload] - 2024-01-16 22:04:05,942 : trigger_reload @ 0266: C:\Users\Администратор\PycharmProjects\24.01_Django\homeworks\projecthome\appfirst\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 22:04:07,085 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-16 22:04:31,348 : trigger_reload @ 0266: C:\Users\Администратор\PycharmProjects\24.01_Django\homeworks\projecthome\appfirst\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 22:04:32,705 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-16 22:04:35,293 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 3687
[INFO    :   django.utils.autoreload] - 2024-01-16 22:07:41,535 : trigger_reload @ 0266: C:\Users\Администратор\PycharmProjects\24.01_Django\homeworks\projecthome\appfirst\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 22:07:42,988 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-16 22:07:57,067 : trigger_reload @ 0266: C:\Users\Администратор\PycharmProjects\24.01_Django\homeworks\projecthome\appfirst\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 22:07:58,249 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-16 22:09:17,265 : trigger_reload @ 0266: C:\Users\Администратор\PycharmProjects\24.01_Django\homeworks\projecthome\appfirst\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 22:09:18,344 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[ERROR   :            django.request] - 2024-01-16 22:09:21,424 : log_response @ 0241: Internal Server Error: /edit_judges/
Traceback (most recent call last):
  File "C:\Users\Администратор\PycharmProjects\24.01_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Администратор\PycharmProjects\24.01_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Администратор\PycharmProjects\24.01_Django\homeworks\projecthome\appfirst\views.py", line 24, in edit_judges
    competition = Judge.competition.throught.filter(judge_id=judge['id']).values_list()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ManyToManyDescriptor' object has no attribute 'throught'
[ERROR   :             django.server] - 2024-01-16 22:09:21,427 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 500 73959
[WARNING :            django.request] - 2024-01-16 22:09:21,599 : log_response @ 0241: Not Found: /favicon.ico
[WARNING :             django.server] - 2024-01-16 22:09:21,601 : log_message @ 0212: "GET /favicon.ico HTTP/1.1" 404 2968
[INFO    :   django.utils.autoreload] - 2024-01-16 22:10:02,940 : trigger_reload @ 0266: C:\Users\Администратор\PycharmProjects\24.01_Django\homeworks\projecthome\appfirst\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 22:10:03,901 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[ERROR   :            django.request] - 2024-01-16 22:10:05,984 : log_response @ 0241: Internal Server Error: /edit_judges/
Traceback (most recent call last):
  File "C:\Users\Администратор\PycharmProjects\24.01_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Администратор\PycharmProjects\24.01_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Администратор\PycharmProjects\24.01_Django\homeworks\projecthome\appfirst\views.py", line 24, in edit_judges
    competition = Judge.competition.throught.objects.filter(judge_id=judge['id']).values_list()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ManyToManyDescriptor' object has no attribute 'throught'
[ERROR   :             django.server] - 2024-01-16 22:10:05,986 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 500 73847
[INFO    :   django.utils.autoreload] - 2024-01-16 22:10:19,871 : trigger_reload @ 0266: C:\Users\Администратор\PycharmProjects\24.01_Django\homeworks\projecthome\appfirst\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 22:10:21,169 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[ERROR   :            django.request] - 2024-01-16 22:10:21,506 : log_response @ 0241: Internal Server Error: /edit_judges/
Traceback (most recent call last):
  File "C:\Users\Администратор\PycharmProjects\24.01_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Администратор\PycharmProjects\24.01_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Администратор\PycharmProjects\24.01_Django\homeworks\projecthome\appfirst\views.py", line 24, in edit_judges
    competition = Judge.competition.objects.filter(judge_id=judge['id']).values_list()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ManyToManyDescriptor' object has no attribute 'objects'
[ERROR   :             django.server] - 2024-01-16 22:10:21,508 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 500 73823
[INFO    :   django.utils.autoreload] - 2024-01-16 22:10:36,211 : trigger_reload @ 0266: C:\Users\Администратор\PycharmProjects\24.01_Django\homeworks\projecthome\appfirst\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 22:10:37,296 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[ERROR   :            django.request] - 2024-01-16 22:10:37,681 : log_response @ 0241: Internal Server Error: /edit_judges/
Traceback (most recent call last):
  File "C:\Users\Администратор\PycharmProjects\24.01_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Администратор\PycharmProjects\24.01_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Администратор\PycharmProjects\24.01_Django\homeworks\projecthome\appfirst\views.py", line 24, in edit_judges
    competition = Judge.competition.filter(judge_id=judge['id']).values_list()
                  ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ManyToManyDescriptor' object has no attribute 'filter'
[ERROR   :             django.server] - 2024-01-16 22:10:37,683 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 500 73801
[ERROR   :            django.request] - 2024-01-16 22:10:47,699 : log_response @ 0241: Internal Server Error: /edit_judges/
Traceback (most recent call last):
  File "C:\Users\Администратор\PycharmProjects\24.01_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Администратор\PycharmProjects\24.01_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Администратор\PycharmProjects\24.01_Django\homeworks\projecthome\appfirst\views.py", line 24, in edit_judges
    competition = Judge.competition.filter(judge_id=judge['id']).values_list()
                  ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ManyToManyDescriptor' object has no attribute 'filter'
[ERROR   :             django.server] - 2024-01-16 22:10:47,701 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 500 73513
[INFO    :   django.utils.autoreload] - 2024-01-16 22:11:14,531 : trigger_reload @ 0266: C:\Users\Администратор\PycharmProjects\24.01_Django\homeworks\projecthome\appfirst\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 22:11:15,681 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[ERROR   :            django.request] - 2024-01-16 22:11:16,182 : log_response @ 0241: Internal Server Error: /edit_judges/
Traceback (most recent call last):
  File "C:\Users\Администратор\PycharmProjects\24.01_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Администратор\PycharmProjects\24.01_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Администратор\PycharmProjects\24.01_Django\homeworks\projecthome\appfirst\views.py", line 24, in edit_judges
    competition = Judge.competition.objects.all()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ManyToManyDescriptor' object has no attribute 'objects'
[ERROR   :             django.server] - 2024-01-16 22:11:16,185 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 500 73578
[INFO    :   django.utils.autoreload] - 2024-01-16 22:12:44,859 : trigger_reload @ 0266: C:\Users\Администратор\PycharmProjects\24.01_Django\homeworks\projecthome\appfirst\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 22:12:46,503 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[ERROR   :            django.request] - 2024-01-16 22:13:07,645 : log_response @ 0241: Internal Server Error: /edit_judges/
Traceback (most recent call last):
  File "C:\Users\Администратор\PycharmProjects\24.01_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Администратор\PycharmProjects\24.01_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Администратор\PycharmProjects\24.01_Django\homeworks\projecthome\appfirst\views.py", line 24, in edit_judges
    competition = Judge.competition.through.objects.all().objects.all()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'QuerySet' object has no attribute 'objects'
[ERROR   :             django.server] - 2024-01-16 22:13:07,647 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 500 73618
[INFO    :   django.utils.autoreload] - 2024-01-16 22:13:40,065 : trigger_reload @ 0266: C:\Users\Администратор\PycharmProjects\24.01_Django\homeworks\projecthome\appfirst\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 22:13:41,103 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-16 22:13:41,363 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 3687
[INFO    :   django.utils.autoreload] - 2024-01-16 22:14:11,882 : trigger_reload @ 0266: C:\Users\Администратор\PycharmProjects\24.01_Django\homeworks\projecthome\appfirst\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 22:14:12,939 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-16 22:14:13,125 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 3687
[INFO    :             django.server] - 2024-01-16 22:14:13,205 : log_message @ 0212: "GET /static/css/stylesheet.css HTTP/1.1" 304 0
[INFO    :   django.utils.autoreload] - 2024-01-16 22:17:02,636 : trigger_reload @ 0266: C:\Users\Администратор\PycharmProjects\24.01_Django\homeworks\projecthome\appfirst\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 22:17:03,804 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-16 22:17:06,436 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 3687
[INFO    :   django.utils.autoreload] - 2024-01-16 22:19:53,654 : trigger_reload @ 0266: C:\Users\Администратор\PycharmProjects\24.01_Django\homeworks\projecthome\appfirst\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 22:19:54,897 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-16 22:19:56,442 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 3687
[INFO    :   django.utils.autoreload] - 2024-01-16 22:24:08,798 : trigger_reload @ 0266: C:\Users\Администратор\PycharmProjects\24.01_Django\homeworks\projecthome\appfirst\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 22:24:09,924 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-16 22:25:02,981 : trigger_reload @ 0266: C:\Users\Администратор\PycharmProjects\24.01_Django\homeworks\projecthome\appfirst\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 22:25:04,643 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-16 22:25:12,286 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 3907
[INFO    :   django.utils.autoreload] - 2024-01-16 22:26:06,638 : trigger_reload @ 0266: C:\Users\Администратор\PycharmProjects\24.01_Django\homeworks\projecthome\appfirst\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 22:26:07,773 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-16 22:26:07,998 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 4395
[INFO    :             django.server] - 2024-01-16 22:26:08,063 : log_message @ 0212: "GET /static/css/stylesheet.css HTTP/1.1" 304 0
[INFO    :   django.utils.autoreload] - 2024-01-16 22:26:26,595 : trigger_reload @ 0266: C:\Users\Администратор\PycharmProjects\24.01_Django\homeworks\projecthome\appfirst\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 22:26:27,869 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-16 22:26:28,191 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 4207
[INFO    :   django.utils.autoreload] - 2024-01-16 22:26:48,936 : trigger_reload @ 0266: C:\Users\Администратор\PycharmProjects\24.01_Django\homeworks\projecthome\appfirst\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 22:26:50,294 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-16 22:26:50,740 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 3889
[INFO    :   django.utils.autoreload] - 2024-01-16 22:30:50,540 : trigger_reload @ 0266: C:\Users\Администратор\PycharmProjects\24.01_Django\homeworks\projecthome\appfirst\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 22:30:51,700 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-16 22:31:59,908 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 3907
[INFO    :   django.utils.autoreload] - 2024-01-16 22:49:15,170 : trigger_reload @ 0266: C:\Users\Администратор\PycharmProjects\24.01_Django\homeworks\projecthome\appfirst\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 22:49:16,608 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-16 22:55:02,367 : trigger_reload @ 0266: C:\Users\Администратор\PycharmProjects\24.01_Django\homeworks\projecthome\appfirst\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 22:55:03,428 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[ERROR   :            django.request] - 2024-01-16 22:55:11,024 : log_response @ 0241: Internal Server Error: /edit_judges/
Traceback (most recent call last):
  File "C:\Users\Администратор\PycharmProjects\24.01_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Администратор\PycharmProjects\24.01_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Администратор\PycharmProjects\24.01_Django\homeworks\projecthome\appfirst\views.py", line 23, in edit_judges
    if comp_dict[comp[1]]:
       ~~~~~~~~~^^^^^^^^^
KeyError: 1
[ERROR   :             django.server] - 2024-01-16 22:55:11,026 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 500 71858
[INFO    :   django.utils.autoreload] - 2024-01-16 22:56:06,833 : trigger_reload @ 0266: C:\Users\Администратор\PycharmProjects\24.01_Django\homeworks\projecthome\appfirst\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 22:56:07,798 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[ERROR   :            django.request] - 2024-01-16 22:56:08,375 : log_response @ 0241: Internal Server Error: /edit_judges/
Traceback (most recent call last):
  File "C:\Users\Администратор\PycharmProjects\24.01_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Администратор\PycharmProjects\24.01_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Администратор\PycharmProjects\24.01_Django\homeworks\projecthome\appfirst\views.py", line 23, in edit_judges
    if comp_dict[comp[1] is not None]:
       ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
KeyError: True
[ERROR   :             django.server] - 2024-01-16 22:56:08,378 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 500 71918
[INFO    :   django.utils.autoreload] - 2024-01-16 22:57:25,951 : trigger_reload @ 0266: C:\Users\Администратор\PycharmProjects\24.01_Django\homeworks\projecthome\appfirst\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 22:57:27,148 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[ERROR   :            django.request] - 2024-01-16 22:57:29,991 : log_response @ 0241: Internal Server Error: /edit_judges/
Traceback (most recent call last):
  File "C:\Users\Администратор\PycharmProjects\24.01_Django\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2112, in get_prep_value
    return int(value)
           ^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'list'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Администратор\PycharmProjects\24.01_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Администратор\PycharmProjects\24.01_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Администратор\PycharmProjects\24.01_Django\homeworks\projecthome\appfirst\views.py", line 33, in edit_judges
    judge['comp'] = Competition.objects.filter(pk=comp_dict[judge['id']]).values_list('name', flat=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Администратор\PycharmProjects\24.01_Django\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Администратор\PycharmProjects\24.01_Django\venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Администратор\PycharmProjects\24.01_Django\venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\Администратор\PycharmProjects\24.01_Django\venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\Администратор\PycharmProjects\24.01_Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1602, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Администратор\PycharmProjects\24.01_Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1634, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Администратор\PycharmProjects\24.01_Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1548, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Администратор\PycharmProjects\24.01_Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1378, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Администратор\PycharmProjects\24.01_Django\venv\Lib\site-packages\django\db\models\lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Администратор\PycharmProjects\24.01_Django\venv\Lib\site-packages\django\db\models\lookups.py", line 362, in get_prep_lookup
    return super().get_prep_lookup()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Администратор\PycharmProjects\24.01_Django\venv\Lib\site-packages\django\db\models\lookups.py", line 88, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Администратор\PycharmProjects\24.01_Django\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2114, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got [1, 2].
[ERROR   :             django.server] - 2024-01-16 22:57:30,004 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 500 136559
[ERROR   :            django.request] - 2024-01-16 22:59:46,618 : log_response @ 0241: Internal Server Error: /edit_judges/
Traceback (most recent call last):
  File "C:\Users\Администратор\PycharmProjects\24.01_Django\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2112, in get_prep_value
    return int(value)
           ^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'list'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Администратор\PycharmProjects\24.01_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Администратор\PycharmProjects\24.01_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Администратор\PycharmProjects\24.01_Django\homeworks\projecthome\appfirst\views.py", line 33, in edit_judges
    judge['comp'] = Competition.objects.filter(pk=comp_dict[judge['id']]).values_list('name', flat=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Администратор\PycharmProjects\24.01_Django\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Администратор\PycharmProjects\24.01_Django\venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Администратор\PycharmProjects\24.01_Django\venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\Администратор\PycharmProjects\24.01_Django\venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\Администратор\PycharmProjects\24.01_Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1602, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Администратор\PycharmProjects\24.01_Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1634, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Администратор\PycharmProjects\24.01_Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1548, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Администратор\PycharmProjects\24.01_Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1378, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Администратор\PycharmProjects\24.01_Django\venv\Lib\site-packages\django\db\models\lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Администратор\PycharmProjects\24.01_Django\venv\Lib\site-packages\django\db\models\lookups.py", line 362, in get_prep_lookup
    return super().get_prep_lookup()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Администратор\PycharmProjects\24.01_Django\venv\Lib\site-packages\django\db\models\lookups.py", line 88, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Администратор\PycharmProjects\24.01_Django\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2114, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got [1].
[ERROR   :             django.server] - 2024-01-16 22:59:46,626 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 500 136504
[INFO    :   django.utils.autoreload] - 2024-01-16 23:00:23,451 : trigger_reload @ 0266: C:\Users\Администратор\PycharmProjects\24.01_Django\homeworks\projecthome\appfirst\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 23:00:24,363 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[ERROR   :            django.request] - 2024-01-16 23:00:26,790 : log_response @ 0241: Internal Server Error: /edit_judges/
Traceback (most recent call last):
  File "C:\Users\Администратор\PycharmProjects\24.01_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Администратор\PycharmProjects\24.01_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Администратор\PycharmProjects\24.01_Django\homeworks\projecthome\appfirst\views.py", line 33, in edit_judges
    judge['comp'] = Competition.objects.filter(pk=comp_dict[judge['id'][0]]).values_list('name', flat=True)
                                                            ~~~~~~~~~~~^^^
TypeError: 'int' object is not subscriptable
[ERROR   :             django.server] - 2024-01-16 23:00:26,794 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 500 74278
[WARNING :            django.request] - 2024-01-16 23:00:27,085 : log_response @ 0241: Not Found: /favicon.ico
[WARNING :             django.server] - 2024-01-16 23:00:27,085 : log_message @ 0212: "GET /favicon.ico HTTP/1.1" 404 2968
[INFO    :   django.utils.autoreload] - 2024-01-16 23:01:28,086 : trigger_reload @ 0266: C:\Users\Администратор\PycharmProjects\24.01_Django\homeworks\projecthome\appfirst\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 23:01:29,719 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-16 23:01:30,616 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 3889
[INFO    :             django.server] - 2024-01-16 23:01:30,769 : log_message @ 0212: "GET /static/css/stylesheet.css HTTP/1.1" 200 6569
[WARNING :            django.request] - 2024-01-16 23:01:30,891 : log_response @ 0241: Not Found: /favicon.ico
[WARNING :             django.server] - 2024-01-16 23:01:30,892 : log_message @ 0212: "GET /favicon.ico HTTP/1.1" 404 2968
[INFO    :   django.utils.autoreload] - 2024-01-16 23:11:38,641 : trigger_reload @ 0266: C:\Users\Администратор\PycharmProjects\24.01_Django\homeworks\projecthome\appfirst\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 23:11:39,759 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-16 23:11:40,452 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 3827
[ERROR   :            django.request] - 2024-01-16 23:12:48,139 : log_response @ 0241: Internal Server Error: /delete_judge/
Traceback (most recent call last):
  File "C:\Users\Администратор\PycharmProjects\24.01_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Администратор\PycharmProjects\24.01_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Users\Администратор\PycharmProjects\24.01_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view appfirst.views.delete_judge didn't return an HttpResponse object. It returned None instead.
[ERROR   :             django.server] - 2024-01-16 23:12:48,140 : log_message @ 0212: "GET /delete_judge/ HTTP/1.1" 500 72350
[INFO    :   django.utils.autoreload] - 2024-01-16 23:13:51,669 : trigger_reload @ 0266: C:\Users\Администратор\PycharmProjects\24.01_Django\homeworks\projecthome\appfirst\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 23:13:52,740 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-16 23:13:54,248 : log_message @ 0212: "GET /delete_judge/ HTTP/1.1" 200 52
[INFO    :   django.utils.autoreload] - 2024-01-16 23:17:33,263 : trigger_reload @ 0266: C:\Users\Администратор\PycharmProjects\24.01_Django\homeworks\projecthome\appfirst\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 23:17:34,616 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-16 23:25:00,796 : trigger_reload @ 0266: C:\Users\Администратор\PycharmProjects\24.01_Django\homeworks\projecthome\appfirst\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 23:25:02,056 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-16 23:26:09,401 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 3845
[INFO    :             django.server] - 2024-01-16 23:26:09,442 : log_message @ 0212: "GET /static/css/stylesheet.css HTTP/1.1" 304 0
[INFO    :            appfirst.views] - 2024-01-16 23:26:12,542 : index @ 0014: Главная страница
[INFO    :             django.server] - 2024-01-16 23:26:12,546 : log_message @ 0212: "GET / HTTP/1.1" 200 1799
[INFO    :             django.server] - 2024-01-16 23:26:12,597 : log_message @ 0212: "GET /static/image/appfirst/cat_1.jpg HTTP/1.1" 304 0
[INFO    :             django.server] - 2024-01-16 23:26:12,598 : log_message @ 0212: "GET /static/image/appfirst/cat_2.jpg HTTP/1.1" 304 0
[INFO    :             django.server] - 2024-01-16 23:26:15,165 : log_message @ 0212: "GET /edit_competitions/ HTTP/1.1" 200 1473
[INFO    :   django.utils.autoreload] - 2024-01-16 23:27:22,285 : trigger_reload @ 0266: C:\Users\Администратор\PycharmProjects\24.01_Django\homeworks\projecthome\appfirst\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 23:27:23,671 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-16 23:27:23,969 : log_message @ 0212: "GET /edit_competitions/ HTTP/1.1" 200 1473
[INFO    :   django.utils.autoreload] - 2024-01-16 23:28:48,716 : trigger_reload @ 0266: C:\Users\Администратор\PycharmProjects\24.01_Django\homeworks\projecthome\appfirst\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 23:28:49,984 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-16 23:28:50,281 : log_message @ 0212: "GET /edit_competitions/ HTTP/1.1" 200 2714
[INFO    :   django.utils.autoreload] - 2024-01-16 23:29:32,379 : trigger_reload @ 0266: C:\Users\Администратор\PycharmProjects\24.01_Django\homeworks\projecthome\appfirst\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 23:29:33,390 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-16 23:30:33,907 : trigger_reload @ 0266: C:\Users\Администратор\PycharmProjects\24.01_Django\homeworks\projecthome\appfirst\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 23:30:35,119 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-16 23:31:55,500 : trigger_reload @ 0266: C:\Users\Администратор\PycharmProjects\24.01_Django\homeworks\projecthome\appfirst\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 23:31:56,553 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-16 23:31:56,809 : log_message @ 0212: "GET /edit_competitions/ HTTP/1.1" 200 1769
[INFO    :   django.utils.autoreload] - 2024-01-16 23:32:49,922 : trigger_reload @ 0266: C:\Users\Администратор\PycharmProjects\24.01_Django\homeworks\projecthome\appfirst\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 23:32:50,863 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-16 23:32:51,076 : log_message @ 0212: "GET /edit_competitions/ HTTP/1.1" 200 3010
[INFO    :   django.utils.autoreload] - 2024-01-16 23:33:12,223 : trigger_reload @ 0266: C:\Users\Администратор\PycharmProjects\24.01_Django\homeworks\projecthome\appfirst\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 23:33:13,266 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-16 23:33:13,578 : log_message @ 0212: "GET /edit_competitions/ HTTP/1.1" 200 3065
[INFO    :             django.server] - 2024-01-16 23:33:20,413 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 3845
[INFO    :   django.utils.autoreload] - 2024-01-16 23:33:51,347 : trigger_reload @ 0266: C:\Users\Администратор\PycharmProjects\24.01_Django\homeworks\projecthome\appfirst\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 23:33:52,430 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-16 23:33:52,803 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 3900
[INFO    :             django.server] - 2024-01-16 23:33:55,606 : log_message @ 0212: "GET /edit_judges/ HTTP/1.1" 200 3900
[INFO    :             django.server] - 2024-01-16 23:34:01,444 : log_message @ 0212: "GET /edit_competitions/ HTTP/1.1" 200 3065
