[INFO    :   django.utils.autoreload] - 2024-01-12 00:21:05,097 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-12 00:21:13,271 : log_message @ 0212: "GET /second/random_digits HTTP/1.1" 200 2
[INFO    :   django.utils.autoreload] - 2024-01-12 00:24:47,294 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\secondapp\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-12 00:24:47,610 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-12 00:24:51,646 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :           secondapp.views] - 2024-01-12 00:24:59,632 : random_digits @ 0024: Случайное граница от 1 до 100
[INFO    :             django.server] - 2024-01-12 00:24:59,633 : log_message @ 0212: "GET /second/random_digits HTTP/1.1" 200 1
[INFO    :           secondapp.views] - 2024-01-12 00:25:06,025 : cube_faces @ 0019: Случайное граница от 1 до 6
[INFO    :             django.server] - 2024-01-12 00:25:06,026 : log_message @ 0212: "GET /second/cube_faces HTTP/1.1" 200 1
[INFO    :           secondapp.views] - 2024-01-12 00:25:07,412 : cube_faces @ 0019: Случайное граница от 1 до 6
[INFO    :             django.server] - 2024-01-12 00:25:07,413 : log_message @ 0212: "GET /second/cube_faces HTTP/1.1" 200 1
[INFO    :   django.utils.autoreload] - 2024-01-12 00:25:44,550 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-12 00:25:59,189 : log_message @ 0212: "GET /first HTTP/1.1" 200 21
[INFO    :           secondapp.views] - 2024-01-12 00:28:02,259 : cube_faces @ 0019: Случайное граница от 1 до 6
[INFO    :             django.server] - 2024-01-12 00:28:02,259 : log_message @ 0212: "GET /second/cube_faces HTTP/1.1" 200 1
[INFO    :   django.utils.autoreload] - 2024-01-12 00:28:55,074 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\secondapp\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-12 00:28:55,395 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :           secondapp.views] - 2024-01-12 00:29:00,690 : heads_and_tails @ 0012: Орел и решка страница
[INFO    :             django.server] - 2024-01-12 00:29:00,690 : log_message @ 0212: "GET /second/heads_and_tails HTTP/1.1" 200 10
[WARNING :            django.request] - 2024-01-12 00:29:37,494 : log_response @ 0241: Not Found: /random_digits
[WARNING :             django.server] - 2024-01-12 00:29:37,495 : log_message @ 0212: "GET /random_digits HTTP/1.1" 404 2338
[INFO    :           secondapp.views] - 2024-01-12 00:29:48,842 : random_digits @ 0024: Случайное число от 1 до 100
[INFO    :             django.server] - 2024-01-12 00:29:48,844 : log_message @ 0212: "GET /second/random_digits HTTP/1.1" 200 2
[INFO    :           secondapp.views] - 2024-01-12 00:29:54,806 : random_digits @ 0024: Случайное число от 1 до 100
[INFO    :             django.server] - 2024-01-12 00:29:54,807 : log_message @ 0212: "GET /second/random_digits HTTP/1.1" 200 2
[INFO    :           secondapp.views] - 2024-01-12 00:29:55,991 : random_digits @ 0024: Случайное число от 1 до 100
[INFO    :             django.server] - 2024-01-12 00:29:55,993 : log_message @ 0212: "GET /second/random_digits HTTP/1.1" 200 2
[INFO    :           secondapp.views] - 2024-01-12 00:29:57,089 : random_digits @ 0024: Случайное число от 1 до 100
[INFO    :             django.server] - 2024-01-12 00:29:57,090 : log_message @ 0212: "GET /second/random_digits HTTP/1.1" 200 2
[INFO    :   django.utils.autoreload] - 2024-01-15 23:23:38,079 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-15 23:24:04,693 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\secondapp\urls.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-15 23:24:06,712 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[WARNING :            django.request] - 2024-01-15 23:24:08,456 : log_response @ 0241: Not Found: /
[WARNING :             django.server] - 2024-01-15 23:24:08,456 : log_message @ 0212: "GET / HTTP/1.1" 404 2277
[WARNING :            django.request] - 2024-01-15 23:24:16,189 : log_response @ 0241: Not Found: /second
[WARNING :             django.server] - 2024-01-15 23:24:16,189 : log_message @ 0212: "GET /second HTTP/1.1" 404 2769
[WARNING :            django.request] - 2024-01-15 23:24:31,889 : log_response @ 0241: Not Found: /second/heads_and_tails
[WARNING :             django.server] - 2024-01-15 23:24:31,889 : log_message @ 0212: "GET /second/heads_and_tails HTTP/1.1" 404 2817
[INFO    :   django.utils.autoreload] - 2024-01-15 23:24:46,574 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\secondapp\urls.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-15 23:24:46,905 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :           secondapp.views] - 2024-01-15 23:24:48,999 : heads_and_tails @ 0014: Орел и решка страница
[INFO    :             django.server] - 2024-01-15 23:24:49,015 : log_message @ 0212: "GET /second/heads_and_tails HTTP/1.1" 200 8
[INFO    :           secondapp.views] - 2024-01-15 23:24:52,822 : heads_and_tails @ 0014: Орел и решка страница
[INFO    :             django.server] - 2024-01-15 23:24:52,828 : log_message @ 0212: "GET /second/heads_and_tails HTTP/1.1" 200 10
[INFO    :   django.utils.autoreload] - 2024-01-15 23:28:04,088 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\secondapp\urls.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-15 23:28:04,435 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-15 23:28:46,247 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\secondapp\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-15 23:28:46,571 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-15 23:30:12,777 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\secondapp\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-15 23:30:13,084 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :           secondapp.views] - 2024-01-15 23:30:19,504 : heads_and_tails @ 0014: Орел и решка страница
[INFO    :             django.server] - 2024-01-15 23:30:19,519 : log_message @ 0212: "GET /second/heads_and_tails HTTP/1.1" 200 8
[WARNING :            django.request] - 2024-01-15 23:30:26,741 : log_response @ 0241: Not Found: /second/ht_results
[WARNING :             django.server] - 2024-01-15 23:30:26,742 : log_message @ 0212: "GET /second/ht_results HTTP/1.1" 404 2999
[ERROR   :            django.request] - 2024-01-15 23:30:46,059 : log_response @ 0241: Internal Server Error: /second/heads_and_tails/result
Traceback (most recent call last):
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\secondapp\views.py", line 26, in ht_results
    for item in all:
TypeError: 'builtin_function_or_method' object is not iterable
[ERROR   :             django.server] - 2024-01-15 23:30:46,060 : log_message @ 0212: "GET /second/heads_and_tails/result HTTP/1.1" 500 64338
[INFO    :   django.utils.autoreload] - 2024-01-15 23:32:00,026 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\secondapp\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-15 23:32:00,355 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-15 23:32:21,305 : log_message @ 0212: "GET /second/heads_and_tails/result HTTP/1.1" 200 173
[INFO    :   django.utils.autoreload] - 2024-01-15 23:33:27,890 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\secondapp\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-15 23:33:28,204 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-15 23:34:05,793 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\secondapp\models.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-15 23:34:06,095 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-15 23:34:19,437 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\secondapp\models.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-15 23:34:19,758 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-15 23:34:21,987 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\secondapp\models.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-15 23:34:22,297 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-15 23:35:11,086 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\secondapp\models.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-15 23:35:11,425 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-15 23:35:17,618 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\secondapp\models.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-15 23:35:17,940 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-15 23:35:24,191 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\secondapp\models.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-15 23:35:24,496 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-15 23:35:28,746 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\secondapp\models.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-15 23:35:29,075 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-15 23:36:35,059 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\secondapp\models.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-15 23:36:35,379 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-15 23:38:02,943 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\secondapp\models.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-15 23:38:03,281 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-15 23:38:07,312 : log_message @ 0212: "GET /second/heads_and_tails/result HTTP/1.1" 200 18
[INFO    :             django.server] - 2024-01-15 23:38:30,982 : log_message @ 0212: "GET /second/heads_and_tails/result HTTP/1.1" 200 18
[INFO    :   django.utils.autoreload] - 2024-01-15 23:40:33,753 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\secondapp\models.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-15 23:40:34,087 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-15 23:40:36,378 : log_message @ 0212: "GET /second/heads_and_tails/result HTTP/1.1" 200 18
[INFO    :           secondapp.views] - 2024-01-15 23:40:42,432 : heads_and_tails @ 0014: Орел и решка страница
[INFO    :             django.server] - 2024-01-15 23:40:42,439 : log_message @ 0212: "GET /second/heads_and_tails HTTP/1.1" 200 8
[INFO    :           secondapp.views] - 2024-01-15 23:40:44,795 : heads_and_tails @ 0014: Орел и решка страница
[INFO    :             django.server] - 2024-01-15 23:40:44,809 : log_message @ 0212: "GET /second/heads_and_tails HTTP/1.1" 200 8
[INFO    :           secondapp.views] - 2024-01-15 23:40:45,870 : heads_and_tails @ 0014: Орел и решка страница
[INFO    :             django.server] - 2024-01-15 23:40:45,877 : log_message @ 0212: "GET /second/heads_and_tails HTTP/1.1" 200 10
[INFO    :             django.server] - 2024-01-15 23:40:58,394 : log_message @ 0212: "GET /second/heads_and_tails/result HTTP/1.1" 200 18
[INFO    :   django.utils.autoreload] - 2024-01-15 23:41:59,608 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\secondapp\models.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-15 23:41:59,957 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-15 23:42:01,872 : log_message @ 0212: "GET /second/heads_and_tails/result HTTP/1.1" 200 18
[INFO    :   django.utils.autoreload] - 2024-01-15 23:42:59,098 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\secondapp\models.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-15 23:42:59,423 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-15 23:43:49,348 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\secondapp\models.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-15 23:43:49,678 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[ERROR   :            django.request] - 2024-01-15 23:44:21,921 : log_response @ 0241: Internal Server Error: /second/heads_and_tails/result
Traceback (most recent call last):
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\secondapp\views.py", line 24, in ht_results
    result = Money.get_data(5)
             ^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\secondapp\models.py", line 15, in get_data
    last_data = Money.objects.all()[-count:]
                ~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\db\models\query.py", line 429, in __getitem__
    raise ValueError("Negative indexing is not supported.")
ValueError: Negative indexing is not supported.
[ERROR   :             django.server] - 2024-01-15 23:44:21,922 : log_message @ 0212: "GET /second/heads_and_tails/result HTTP/1.1" 500 71823
[INFO    :   django.utils.autoreload] - 2024-01-15 23:45:01,015 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\secondapp\models.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-15 23:45:01,340 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-15 23:46:13,703 : log_message @ 0212: "GET /second/heads_and_tails/result HTTP/1.1" 200 18
[INFO    :   django.utils.autoreload] - 2024-01-15 23:47:27,756 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\secondapp\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-15 23:47:28,093 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-15 23:47:41,500 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\secondapp\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-15 23:47:41,826 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-15 23:47:43,611 : log_message @ 0212: "GET /second/heads_and_tails/result HTTP/1.1" 200 68
[INFO    :           secondapp.views] - 2024-01-15 23:47:58,258 : heads_and_tails @ 0015: Орел и решка страница
[INFO    :             django.server] - 2024-01-15 23:47:58,265 : log_message @ 0212: "GET /second/heads_and_tails HTTP/1.1" 200 8
[INFO    :   django.utils.autoreload] - 2024-01-15 23:48:34,902 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\secondapp\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-15 23:48:35,224 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :           secondapp.views] - 2024-01-15 23:48:36,946 : heads_and_tails @ 0015: Орел и решка страница
[INFO    :             django.server] - 2024-01-15 23:48:36,962 : log_message @ 0212: "GET /second/heads_and_tails HTTP/1.1" 200 10
[INFO    :             django.server] - 2024-01-15 23:48:48,692 : log_message @ 0212: "GET /second/heads_and_tails/result HTTP/1.1" 200 32
[INFO    :             django.server] - 2024-01-15 23:49:36,376 : log_message @ 0212: "GET /second/heads_and_tails/result HTTP/1.1" 200 32
[INFO    :             django.server] - 2024-01-15 23:49:42,534 : log_message @ 0212: "GET /second/heads_and_tails/result HTTP/1.1" 200 32
[WARNING :            django.request] - 2024-01-15 23:49:42,568 : log_response @ 0241: Not Found: /favicon.ico
[WARNING :             django.server] - 2024-01-15 23:49:42,569 : log_message @ 0212: "GET /favicon.ico HTTP/1.1" 404 2328
[INFO    :   django.utils.autoreload] - 2024-01-15 23:50:03,839 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\secondapp\models.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-15 23:50:04,174 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-15 23:50:45,977 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\secondapp\models.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-15 23:50:46,314 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[ERROR   :            django.request] - 2024-01-15 23:50:49,829 : log_response @ 0241: Internal Server Error: /second/heads_and_tails/result
Traceback (most recent call last):
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\secondapp\views.py", line 25, in ht_results
    result = Money.get_data(5)
             ^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\secondapp\models.py", line 15, in get_data
    last_data = Money.objects.all()[len(Money.objects.all()-count):]
                                        ~~~~~~~~~~~~~~~~~~~^~~~~~
TypeError: unsupported operand type(s) for -: 'QuerySet' and 'int'
[ERROR   :             django.server] - 2024-01-15 23:50:49,831 : log_message @ 0212: "GET /second/heads_and_tails/result HTTP/1.1" 500 67744
[INFO    :   django.utils.autoreload] - 2024-01-15 23:51:06,929 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\secondapp\models.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-15 23:51:07,264 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-15 23:51:07,720 : log_message @ 0212: "GET /second/heads_and_tails/result HTTP/1.1" 200 32
[INFO    :   django.utils.autoreload] - 2024-01-15 23:53:27,503 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\secondapp\models.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-15 23:53:27,850 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-15 23:53:46,338 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\secondapp\models.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-15 23:53:46,639 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-15 23:56:47,032 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\secondapp\models.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-15 23:56:47,388 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-15 23:57:16,007 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\secondapp\models.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-15 23:57:16,335 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-15 23:57:31,776 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\secondapp\models.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-15 23:57:32,123 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-15 23:57:42,514 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\secondapp\models.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-15 23:57:42,849 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-15 23:59:13,385 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\secondapp\models.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-15 23:59:13,721 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-16 00:09:57,014 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-16 00:10:25,633 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\secondapp\models.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 00:10:25,964 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-16 00:11:01,715 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\secondapp\models.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 00:11:02,033 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-16 00:15:12,274 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\secondapp\models.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 00:15:12,611 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-16 00:32:09,029 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[WARNING :            django.request] - 2024-01-16 00:32:10,937 : log_response @ 0241: Not Found: /
[WARNING :             django.server] - 2024-01-16 00:32:10,938 : log_message @ 0212: "GET / HTTP/1.1" 404 2279
[WARNING :            django.request] - 2024-01-16 00:32:22,406 : log_response @ 0241: Not Found: /authors
[WARNING :             django.server] - 2024-01-16 00:32:22,407 : log_message @ 0212: "GET /authors HTTP/1.1" 404 2318
[ERROR   :            django.request] - 2024-01-16 00:32:32,085 : log_response @ 0241: Internal Server Error: /second/authors
Traceback (most recent call last):
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\secondapp\views.py", line 41, in authors_view
    authors = Author.objects.all()
              ^^^^^^
NameError: name 'Author' is not defined
[ERROR   :             django.server] - 2024-01-16 00:32:32,086 : log_message @ 0212: "GET /second/authors HTTP/1.1" 500 63645
[INFO    :   django.utils.autoreload] - 2024-01-16 00:33:08,290 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\secondapp\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 00:33:08,608 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[ERROR   :            django.request] - 2024-01-16 00:33:08,832 : log_response @ 0241: Internal Server Error: /second/authors
Traceback (most recent call last):
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\secondapp\views.py", line 42, in authors_view
    res_str = '\n'.join(author for author in authors)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: sequence item 0: expected str instance, Author found
[ERROR   :             django.server] - 2024-01-16 00:33:08,833 : log_message @ 0212: "GET /second/authors HTTP/1.1" 500 64755
[INFO    :   django.utils.autoreload] - 2024-01-16 00:35:15,856 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\secondapp\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-16 00:35:16,268 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[ERROR   :            django.request] - 2024-01-16 00:35:18,999 : log_response @ 0241: Internal Server Error: /second/authors
Traceback (most recent call last):
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\secondapp\views.py", line 42, in authors_view
    res_str = '\n'.join(author for author in authors)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: sequence item 0: expected str instance, Author found
[ERROR   :             django.server] - 2024-01-16 00:35:19,001 : log_message @ 0212: "GET /second/authors HTTP/1.1" 500 64760
[INFO    :   django.utils.autoreload] - 2024-01-16 00:51:09,462 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[WARNING :            django.request] - 2024-01-16 00:51:10,653 : log_response @ 0241: Not Found: /
[WARNING :             django.server] - 2024-01-16 00:51:10,654 : log_message @ 0212: "GET / HTTP/1.1" 404 2279
[INFO    :             django.server] - 2024-01-16 00:51:29,805 : log_message @ 0212: "GET /second/authors HTTP/1.1" 200 415
[INFO    :             django.server] - 2024-01-16 00:51:35,860 : log_message @ 0212: "GET /second/posts HTTP/1.1" 200 4161
[INFO    :             django.server] - 2024-01-16 00:51:43,900 : log_message @ 0212: "GET /second/authors HTTP/1.1" 200 415
[INFO    :   django.utils.autoreload] - 2024-01-18 23:17:33,151 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[WARNING :            django.request] - 2024-01-18 23:17:35,835 : log_response @ 0241: Not Found: /
[WARNING :             django.server] - 2024-01-18 23:17:35,835 : log_message @ 0212: "GET / HTTP/1.1" 404 2279
[INFO    :             django.server] - 2024-01-18 23:17:45,024 : log_message @ 0212: "GET /second HTTP/1.1" 301 0
[ERROR   :            django.request] - 2024-01-18 23:17:45,048 : log_response @ 0241: Internal Server Error: /second/
Traceback (most recent call last):
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\secondapp\views.py", line 54, in index_view
    return render(request, 'index.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
[ERROR   :             django.server] - 2024-01-18 23:17:45,050 : log_message @ 0212: "GET /second/ HTTP/1.1" 500 77958
[INFO    :   django.utils.autoreload] - 2024-01-18 23:18:05,142 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\secondapp\urls.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-18 23:18:05,468 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[ERROR   :            django.request] - 2024-01-18 23:18:06,114 : log_response @ 0241: Internal Server Error: /second/
Traceback (most recent call last):
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\secondapp\views.py", line 54, in index_view
    return render(request, 'index.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
[ERROR   :             django.server] - 2024-01-18 23:18:06,116 : log_message @ 0212: "GET /second/ HTTP/1.1" 500 78095
[ERROR   :            django.request] - 2024-01-18 23:18:06,782 : log_response @ 0241: Internal Server Error: /second/
Traceback (most recent call last):
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\secondapp\views.py", line 54, in index_view
    return render(request, 'index.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
[ERROR   :             django.server] - 2024-01-18 23:18:06,784 : log_message @ 0212: "GET /second/ HTTP/1.1" 500 78095
[INFO    :   django.utils.autoreload] - 2024-01-18 23:18:38,256 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\secondapp\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-18 23:18:38,576 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[ERROR   :            django.request] - 2024-01-18 23:18:38,759 : log_response @ 0241: Internal Server Error: /second/
Traceback (most recent call last):
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\secondapp\views.py", line 54, in index_view
    return render(request, 'secondapp/index.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
[ERROR   :             django.server] - 2024-01-18 23:18:38,763 : log_message @ 0212: "GET /second/ HTTP/1.1" 500 127869
[INFO    :   django.utils.autoreload] - 2024-01-18 23:19:10,022 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[WARNING :            django.request] - 2024-01-18 23:19:11,307 : log_response @ 0241: Not Found: /
[WARNING :             django.server] - 2024-01-18 23:19:11,308 : log_message @ 0212: "GET / HTTP/1.1" 404 2279
[INFO    :             django.server] - 2024-01-18 23:19:17,719 : log_message @ 0212: "GET /second/authors HTTP/1.1" 200 415
[ERROR   :            django.request] - 2024-01-18 23:19:25,673 : log_response @ 0241: Internal Server Error: /second/
Traceback (most recent call last):
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\secondapp\views.py", line 54, in index_view
    return render(request, 'secondapp/index.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
[ERROR   :             django.server] - 2024-01-18 23:19:25,677 : log_message @ 0212: "GET /second/ HTTP/1.1" 500 127732
[ERROR   :            django.request] - 2024-01-18 23:19:49,430 : log_response @ 0241: Internal Server Error: /second/
Traceback (most recent call last):
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\secondapp\views.py", line 54, in index_view
    return render(request, 'secondapp/index.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
[ERROR   :             django.server] - 2024-01-18 23:19:49,434 : log_message @ 0212: "GET /second/ HTTP/1.1" 500 127869
[INFO    :   django.utils.autoreload] - 2024-01-18 23:20:25,790 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\sem_1_project\settings.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-18 23:20:26,106 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-18 23:20:26,346 : log_message @ 0212: "GET /second/ HTTP/1.1" 200 239
[INFO    :   django.utils.autoreload] - 2024-01-18 23:24:12,967 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-18 23:26:28,464 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\thirdapp\urls.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-18 23:26:28,800 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-18 23:26:29,567 : log_message @ 0212: "GET /second/ HTTP/1.1" 200 285
[WARNING :            django.request] - 2024-01-18 23:26:37,474 : log_response @ 0241: Not Found: /third
[WARNING :             django.server] - 2024-01-18 23:26:37,475 : log_message @ 0212: "GET /third HTTP/1.1" 404 2418
[WARNING :            django.request] - 2024-01-18 23:26:49,703 : log_response @ 0241: Not Found: /third/
[WARNING :             django.server] - 2024-01-18 23:26:49,703 : log_message @ 0212: "GET /third/ HTTP/1.1" 404 2489
[INFO    :   django.utils.autoreload] - 2024-01-18 23:29:22,075 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\thirdapp\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-18 23:29:22,412 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[WARNING :            django.request] - 2024-01-18 23:29:23,339 : log_response @ 0241: Not Found: /third/
[WARNING :             django.server] - 2024-01-18 23:29:23,339 : log_message @ 0212: "GET /third/ HTTP/1.1" 404 2489
[WARNING :            django.request] - 2024-01-18 23:29:45,911 : log_response @ 0241: Not Found: /third/
[WARNING :             django.server] - 2024-01-18 23:29:45,912 : log_message @ 0212: "GET /third/ HTTP/1.1" 404 2489
[INFO    :   django.utils.autoreload] - 2024-01-18 23:29:46,018 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\thirdapp\urls.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-18 23:29:46,339 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[ERROR   :            django.request] - 2024-01-18 23:29:50,830 : log_response @ 0241: Internal Server Error: /third/
Traceback (most recent call last):
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\thirdapp\views.py", line 9, in third_index
    return render(request, 'third/index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: third/index.html
[ERROR   :             django.server] - 2024-01-18 23:29:50,832 : log_message @ 0212: "GET /third/ HTTP/1.1" 500 78719
[INFO    :   django.utils.autoreload] - 2024-01-18 23:30:08,929 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[WARNING :            django.request] - 2024-01-18 23:30:15,657 : log_response @ 0241: Not Found: /
[WARNING :             django.server] - 2024-01-18 23:30:15,657 : log_message @ 0212: "GET / HTTP/1.1" 404 2385
[INFO    :             django.server] - 2024-01-18 23:30:25,079 : log_message @ 0212: "GET /third HTTP/1.1" 301 0
[ERROR   :            django.request] - 2024-01-18 23:30:25,102 : log_response @ 0241: Internal Server Error: /third/
Traceback (most recent call last):
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\thirdapp\views.py", line 9, in third_index
    return render(request, 'third/index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: third/index.html
[ERROR   :             django.server] - 2024-01-18 23:30:25,104 : log_message @ 0212: "GET /third/ HTTP/1.1" 500 78582
[INFO    :   django.utils.autoreload] - 2024-01-18 23:31:25,668 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\thirdapp\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-18 23:31:26,012 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-18 23:31:26,737 : log_message @ 0212: "GET /third/ HTTP/1.1" 200 269
[INFO    :   django.utils.autoreload] - 2024-01-18 23:32:55,791 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\thirdapp\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-18 23:32:56,116 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-18 23:44:49,242 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\thirdapp\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-18 23:44:49,558 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[WARNING :            django.request] - 2024-01-18 23:44:50,953 : log_response @ 0241: Not Found: /
[WARNING :             django.server] - 2024-01-18 23:44:50,953 : log_message @ 0212: "GET / HTTP/1.1" 404 2385
[INFO    :             django.server] - 2024-01-18 23:45:03,920 : log_message @ 0212: "GET /third/ HTTP/1.1" 200 269
[WARNING :            django.request] - 2024-01-18 23:45:15,667 : log_response @ 0241: Not Found: /third/heads_and_tails/4
[WARNING :             django.server] - 2024-01-18 23:45:15,667 : log_message @ 0212: "GET /third/heads_and_tails/4 HTTP/1.1" 404 2732
[INFO    :   django.utils.autoreload] - 2024-01-18 23:45:32,712 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\thirdapp\urls.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-18 23:45:33,031 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[ERROR   :            django.request] - 2024-01-18 23:45:35,077 : log_response @ 0241: Internal Server Error: /third/heads_and_tails/4/
Traceback (most recent call last):
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 502, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\thirdapp\views.py", line 19, in heads_and_tails
    return render(request, 'thirdapp/heads_and_tails.html', context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 504, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 565, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 3: 'title'. Did you forget to register or load this tag?
[ERROR   :             django.server] - 2024-01-18 23:45:35,081 : log_message @ 0212: "GET /third/heads_and_tails/4/ HTTP/1.1" 500 150414
[INFO    :             django.server] - 2024-01-18 23:45:46,810 : log_message @ 0212: "GET /third/heads_and_tails/4/ HTTP/1.1" 200 255
[INFO    :   django.utils.autoreload] - 2024-01-18 23:47:06,129 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\thirdapp\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-18 23:47:06,456 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-18 23:47:50,516 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\thirdapp\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-18 23:47:50,833 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-18 23:47:51,069 : log_message @ 0212: "GET /third/heads_and_tails/4/ HTTP/1.1" 200 255
[INFO    :   django.utils.autoreload] - 2024-01-18 23:48:08,365 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\thirdapp\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-18 23:48:08,688 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-18 23:48:08,808 : log_message @ 0212: "GET /third/heads_and_tails/4/ HTTP/1.1" 200 365
[INFO    :   django.utils.autoreload] - 2024-01-18 23:48:13,997 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\thirdapp\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-18 23:48:14,342 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-18 23:49:27,902 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\thirdapp\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-18 23:49:28,252 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-18 23:50:47,924 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\thirdapp\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-18 23:50:48,240 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-18 23:52:11,974 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\thirdapp\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-18 23:52:12,327 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-18 23:52:54,593 : log_message @ 0212: "GET /third/heads_and_tails/8/ HTTP/1.1" 200 475
[INFO    :   django.utils.autoreload] - 2024-01-18 23:58:06,284 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\thirdapp\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-18 23:58:06,647 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-18 23:59:36,216 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\thirdapp\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-18 23:59:36,536 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-18 23:59:38,776 : log_message @ 0212: "GET /third/heads_and_tails/8/ HTTP/1.1" 200 480
[INFO    :             django.server] - 2024-01-18 23:59:45,883 : log_message @ 0212: "GET /third/ HTTP/1.1" 200 269
[WARNING :            django.request] - 2024-01-18 23:59:58,522 : log_response @ 0241: Not Found: /third/cube_face/4/
[WARNING :             django.server] - 2024-01-18 23:59:58,522 : log_message @ 0212: "GET /third/cube_face/4/ HTTP/1.1" 404 3141
[WARNING :            django.request] - 2024-01-19 00:00:04,703 : log_response @ 0241: Not Found: /third/cube_faces/4/
[WARNING :             django.server] - 2024-01-19 00:00:04,704 : log_message @ 0212: "GET /third/cube_faces/4/ HTTP/1.1" 404 3144
[WARNING :            django.request] - 2024-01-19 00:00:41,141 : log_response @ 0241: Not Found: /third/ cube_faces/4/
[WARNING :             django.server] - 2024-01-19 00:00:41,142 : log_message @ 0212: "GET /third/%20cube_faces/4/ HTTP/1.1" 404 3149
[INFO    :   django.utils.autoreload] - 2024-01-19 00:01:15,649 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\thirdapp\urls.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-19 00:01:15,972 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[WARNING :            django.request] - 2024-01-19 00:01:16,202 : log_response @ 0241: Not Found: /third/ cube_faces/4/
[WARNING :             django.server] - 2024-01-19 00:01:16,203 : log_message @ 0212: "GET /third/%20cube_faces/4/ HTTP/1.1" 404 3151
[INFO    :   django.utils.autoreload] - 2024-01-19 00:01:43,935 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[WARNING :            django.request] - 2024-01-19 00:01:46,941 : log_response @ 0241: Not Found: /third/ cube_faces/4/
[WARNING :             django.server] - 2024-01-19 00:01:46,941 : log_message @ 0212: "GET /third/%20cube_faces/4/ HTTP/1.1" 404 3151
[WARNING :            django.request] - 2024-01-19 00:02:57,884 : log_response @ 0241: Not Found: /third/ cube_faces/4/
[WARNING :             django.server] - 2024-01-19 00:02:57,884 : log_message @ 0212: "GET /third/%20cube_faces/4/ HTTP/1.1" 404 3151
[INFO    :             django.server] - 2024-01-19 00:03:05,330 : log_message @ 0212: "GET /third/heads_and_tails/3/ HTTP/1.1" 200 343
[INFO    :             django.server] - 2024-01-19 00:03:18,908 : log_message @ 0212: "GET /third/cube_faces/3/ HTTP/1.1" 200 261
[INFO    :             django.server] - 2024-01-19 00:03:33,723 : log_message @ 0212: "GET /third/random_digits/5/ HTTP/1.1" 200 265
[INFO    :   django.utils.autoreload] - 2024-01-19 00:05:46,603 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\thirdapp\models.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-19 00:05:46,934 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-19 00:20:06,433 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-19 00:20:20,781 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\thirdapp\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-19 00:20:21,095 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-19 00:20:23,277 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-19 00:22:24,835 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\thirdapp\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-19 00:22:25,156 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-19 00:22:38,918 : log_message @ 0212: "GET /third/random_digits/5/ HTTP/1.1" 200 265
[ERROR   :            django.request] - 2024-01-19 00:22:46,046 : log_response @ 0241: Internal Server Error: /third/author_post/
Traceback (most recent call last):
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: author_post() missing 1 required positional argument: 'author_id'
[ERROR   :             django.server] - 2024-01-19 00:22:46,047 : log_message @ 0212: "GET /third/author_post/ HTTP/1.1" 500 60472
[INFO    :   django.utils.autoreload] - 2024-01-19 00:23:22,646 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\thirdapp\urls.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-19 00:23:22,970 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[ERROR   :            django.request] - 2024-01-19 00:23:27,547 : log_response @ 0241: Internal Server Error: /third/author_post/3/
Traceback (most recent call last):
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\thirdapp\views.py", line 42, in author_post
    return render(request, 'thirdapp/author_post.html', context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: thirdapp/author_post.html
[ERROR   :             django.server] - 2024-01-19 00:23:27,549 : log_message @ 0212: "GET /third/author_post/3/ HTTP/1.1" 500 82647
[ERROR   :            django.request] - 2024-01-19 00:25:15,049 : log_response @ 0241: Internal Server Error: /third/author_post/3/
Traceback (most recent call last):
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 502, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'endbblock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\thirdapp\views.py", line 42, in author_post
    return render(request, 'thirdapp/author_post.html', context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 504, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 555, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 7: 'endbblock', expected 'endblock'. Did you forget to register or load this tag?
[ERROR   :             django.server] - 2024-01-19 00:25:15,053 : log_message @ 0212: "GET /third/author_post/3/ HTTP/1.1" 500 162300
[INFO    :             django.server] - 2024-01-19 00:25:23,776 : log_message @ 0212: "GET /third/author_post/3/ HTTP/1.1" 200 190
[ERROR   :            django.request] - 2024-01-19 00:27:55,862 : log_response @ 0241: Internal Server Error: /third/author_post/3/
Traceback (most recent call last):
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 502, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'endblock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\thirdapp\views.py", line 42, in author_post
    return render(request, 'thirdapp/author_post.html', context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\defaulttags.py", line 860, in do_for
    nodelist_loop = parser.parse(
                    ^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 504, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 555, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 13: 'endblock', expected 'empty' or 'endfor'. Did you forget to register or load this tag?
[ERROR   :             django.server] - 2024-01-19 00:27:55,866 : log_message @ 0212: "GET /third/author_post/3/ HTTP/1.1" 500 181553
[INFO    :             django.server] - 2024-01-19 00:28:12,611 : log_message @ 0212: "GET /third/author_post/3/ HTTP/1.1" 200 988
[INFO    :             django.server] - 2024-01-19 00:28:25,897 : log_message @ 0212: "GET /third/author_post/4/ HTTP/1.1" 200 988
[INFO    :   django.utils.autoreload] - 2024-01-19 00:36:18,101 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\thirdapp\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-19 00:36:18,444 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[WARNING :            django.request] - 2024-01-19 00:39:01,322 : log_response @ 0241: Not Found: /
[WARNING :             django.server] - 2024-01-19 00:39:01,323 : log_message @ 0212: "GET / HTTP/1.1" 404 2385
[ERROR   :            django.request] - 2024-01-19 00:39:16,376 : log_response @ 0241: Internal Server Error: /third/author_post/4/
Traceback (most recent call last):
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\thirdapp\views.py", line 41, in author_post
    return render(request, 'thirdapp/author_post.html', context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\defaulttags.py", line 241, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\defaulttags.py", line 325, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\defaulttags.py", line 478, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\urls\resolvers.py", line 848, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'post' with arguments '('',)' not found. 1 pattern(s) tried: ['third/post/(?P<post_id>[0-9]+)/\\Z']
[ERROR   :             django.server] - 2024-01-19 00:39:16,381 : log_message @ 0212: "GET /third/author_post/4/ HTTP/1.1" 500 208396
[INFO    :   django.utils.autoreload] - 2024-01-19 00:40:32,737 : trigger_reload @ 0266: C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\thirdapp\urls.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-19 00:40:33,065 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[ERROR   :            django.request] - 2024-01-19 00:40:33,339 : log_response @ 0241: Internal Server Error: /third/author_post/4/
Traceback (most recent call last):
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\seminars\sem_1\sem_1_project\thirdapp\views.py", line 41, in author_post
    return render(request, 'thirdapp/author_post.html', context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\defaulttags.py", line 241, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\defaulttags.py", line 325, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\template\defaulttags.py", line 478, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GeekBrains\II_quarter\24_01_Django\.venv\Lib\site-packages\django\urls\resolvers.py", line 848, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'post_view' with arguments '('',)' not found. 1 pattern(s) tried: ['third/post/(?P<post_id>[0-9]+)/\\Z']
[ERROR   :             django.server] - 2024-01-19 00:40:33,344 : log_message @ 0212: "GET /third/author_post/4/ HTTP/1.1" 500 208633
[INFO    :             django.server] - 2024-01-19 00:42:08,327 : log_message @ 0212: "GET /third/author_post/4/ HTTP/1.1" 200 1196
[INFO    :             django.server] - 2024-01-19 00:43:37,476 : log_message @ 0212: "GET /third/post/27/ HTTP/1.1" 200 213
[INFO    :             django.server] - 2024-01-19 00:43:44,131 : log_message @ 0212: "GET /third/post/27/ HTTP/1.1" 200 213
